### ISSUE TITLE
Unable to use image from Azure Container Registry

### ISSUE THREAD

**Issue by jsheetzati** [microsoft/azure-container-apps#10]
Hello,

I am trying to use an existing image from our Azure Container Registry and getting this error message when creating the ContainerApp resource in the Azure Portal. I also tried specifying this image as part of a revision to the ContainerApp but get the same error.

![image](https://user-images.githubusercontent.com/15350893/140427766-6501602e-226d-4474-abf2-6734b0f6633e.png)

**Comment by tomkerkhove** [comment]
Isn't this error more because the name of a secret is too long?

**Comment by jsheetzati** [comment]
I am not sure where this secret value is coming from. I don't explicitly set it anywhere. I get a similar error using AZ CLI.

cli.azure.cli.core.azclierror: The following field(s) are invalid: configuration.secrets : "***registryazurecrio-***registry": Length must be no more than 63 characters.

CLI command:
```
 az containerapp update --name ***-webapi-container --resource-group *** --image webapi:test-1.0.0 --debug --registry-login-server ***registry.azurecr.io --registry-username *** --registry-password ***
```

**Comment by vturecek** [comment]
The CLI automatically creates a secret when you use `--registry-password` so that your password is securely stored. The auto-generated secret concats the registry name and username which can sometimes exceed the 63-character limit on secret names. We are working on lifting this 63-character limit on secret names.

The way around this for now is to create a secret of your own and then reference it in the registry password. Unfortunately it looks like there is a bug in the `--registry-password` parameter in the CLI when referencing a secret (fix should be out soon), so for now you can do it declaratively in yaml:

```
az containerapp create --resource-group myrg --name myapp --yaml app.yaml
```

app.yaml:
```
kubeEnvironmentId: /subscriptions/<subscription>/resourceGroups/<rg>/providers/Microsoft.Web/kubeEnvironments/<environment name>
configuration:
  activeRevisionsMode: multiple
  registries:
  - server: myacr.azurecr.io
    username: someuser
    passwordSecretRef: acr-password
  secrets:
  - name: acr-password
    value: <PasswordGoesHere>
template:
  containers:
  - image: myacr.azurecr.io/myimage:tag
    name: myimage
    resources:
      cpu: 0.5
      memory: 1Gi
  scale:
    maxReplicas: 1
    minReplicas: 0

```
