### ISSUE TITLE
Dapr sidecar configuration

### ISSUE THREAD

**Issue by hinter-man** [microsoft/azure-container-apps#100]
Is it possible to [configure the dapr sidecar](https://docs.dapr.io/operations/configuration/configuration-overview/)? 
For example to configure tracing. In my local development environment (with docker compose) I have a configuration file like this:
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-config
  namespace: default
spec:
  tracing:
    enabled: true
    samplingRate: "1"
    expandParams: true
    includeBody: true
    zipkin:
      endpointAddress: http://zipkin:9411/api/v2/spans
```

In my specific case I try to collect traces and push them to Azure Application Insights. This [link](https://docs.dapr.io/operations/monitoring/tracing/open-telemetry-collector-appinsights/) shows how it is done with kubernetes.
Is this possible with Azure Container Apps?
