### ISSUE TITLE
edit ACA Job from the portal

### ISSUE THREAD

**Issue by jason-berk-k1x** [microsoft/azure-container-apps#1046]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
the portal provides an "Edit" UI to modify job settings but doesn't allow you to save them.  For example, I go to my job, look at the "containers" section, select my container and click "Edit", and modify my ENV variables, CPU, Memory, etc......but the SAVE button is always disabled.

### Steps to reproduce
1. create a container app job
2. open the job in the portal
3. view its containers
4. select the container and click "edit"
5. make a change to the CPU or memory settings 

**Expected behavior** [What you expected to happen.]

the SAVE button enables and you can save your edits

**Actual behavior** [What actually happened.]

the SAVE button never enables.  when you try to navigate away from the page, you get a browser warning about unsaved changes

**Screenshots**         

![Screenshot 2024-01-04 at 11 37 19 AM](https://github.com/microsoft/azure-container-apps/assets/148882427/a0105e7c-2e94-4a69-91ab-d84dc1f11999)

![Screenshot 2024-01-04 at 11 37 39 AM](https://github.com/microsoft/azure-container-apps/assets/148882427/0529c5d9-1fa3-456f-a34b-a92b329b00d9)

![Screenshot 2024-01-04 at 11 43 12 AM](https://github.com/microsoft/azure-container-apps/assets/148882427/5c328151-d3ce-402a-91df-9468dfedb0fd)

![Screenshot 2024-01-04 at 11 51 08 AM](https://github.com/microsoft/azure-container-apps/assets/148882427/e2fb568e-f45e-4bb8-bc77-eb900f629ffb)

### Additional context

I can make the desired changes from the CLI, but not from the portal.  

I also confirmed the same basic workflow *does* work in the portal for an "app"....just not for a job

**Comment by jason-berk-k1x** [comment]
so the plot thickens......

I use Terraform to create the ACA Job (using the AzApi provider).  The created job is the public image for the manually triggered job as referenced [here](https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-cli#manual-jobs)

```
resource "azapi_resource" "job" {
  type      = "Microsoft.App/jobs@2023-05-01"
  name      = var.job_name
  parent_id = azurerm_resource_group.job_rg.id
  location  = azurerm_resource_group.job_rg.location
  tags = merge(local.standard_tags, var.supplemental_tags)
  
  identity {
    type = "SystemAssigned"
  }

  body = jsonencode({
   "properties": {
      "configuration": {
          "manualTriggerConfig": {
              "parallelism": 1,
              "replicaCompletionCount": 1
          },
          "replicaRetryLimit": 0,
          "replicaTimeout": 30,
          "triggerType": "Manual"
      },
      "environmentId": "${data.azurerm_container_app_environment.ace.id}",
      "template": {
          "containers": [
              {
                  "image": "mcr.microsoft.com/k8se/quickstart-jobs:latest",
                  "name": "main",
                  "resources": {
                      "cpu": 0.25,
                      "memory": "0.5Gi"
                  }
              }
          ]
      }
    } 
  })

  response_export_values    = ["*"]
#   schema_validation_enabled = false
  
  ignore_body_changes       = [
    "properties.template.containers",
    "properties.configuration",
    "properties.template"
  ]

  lifecycle {
    ignore_changes = all
  }
}
```

then, I have a pipeline that executes the following CLI command to update the job:

> az containerapp job update --name the-job-name --resource-group the-job-name-rg --yaml config.yml

where the `config.yml` has

```
# schema at
# https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2023-05-01/jobs?pivots=deployment-language-arm-template#resource-format-1
# examples at
# https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-cli#job-settings

name: the-job-name
properties:
  managedEnvironmentId: <the ACA env ref>
  configuration:
    triggerType: Event
    replicaRetryLimit: 0
    replicaTimeout: 900
    eventTriggerConfig:
      # replicaCompletionCount: 1
      # parallelism: 1
      scale:
        # minExecutions: 0
        maxExecutions: 10
        pollingInterval: 10
        rules:
          - name: queue-based
            type: azure-servicebus
            metadata:
              queueName: some-queue-name
              messageCount: "1"
            auth:
              - secretRef: service-bus-connection
                triggerParameter: connection
    registries:
      - server: our-acr-host.azurecr.io
        identity: system
    secrets:
      - name: service-bus-connection
        keyVaultUrl: <key vault url>
        identity: system
  template: 
    containers:
      - image: acrk1x001.azurecr.io/readerv2:{{V2_DOCKER_TAG}}
        name: worker
        command:
          - python
          - -m
          - worker
        resources:
          cpu: 1
          memory: 2Gi
        env:
          - name: IMAGE
            value: our-acr-host.azurecr.io/k1readerv2:{{V2_DOCKER_TAG}}
          - name: BLOB_CONNECTION_STRING
            secretRef: blob-connection
```

I run my pipeline and deploy a container from our ACR instance....everything works

this allows us to create generic jobs and manage all the infra with TF but allows the engineers to manage the specific image and job details via the config file and pipeline runs.  As you can see above, running the pipeline updates the image, the registry to pull the image from and any other job specific details that can change and should be managed outside of TF.

now, I want to let a developer edit the container from the portal, to update an ENV variable, for example.  Devs like to make these sorts of changes in the portal and "see if it works" before they spend their time making a branch, pushing it, and running the pipeline.

I see this:

![Screenshot 2024-01-04 at 12 26 04 PM](https://github.com/microsoft/azure-container-apps/assets/148882427/fa04d991-4ae4-43f6-a9d9-85d9bfa58964)

notice, the Registry / Image / Tag values are required, but unset....and image source is `Azure Container Registry`

if I change it to `Docker Hub or other registries` the registry login server automatically fills with my ACR instance and the correct image tag is pre filled as well, and the save button becomes enabled

![Screenshot 2024-01-04 at 12 32 10 PM](https://github.com/microsoft/azure-container-apps/assets/148882427/34547dab-d696-4c8c-98a4-5e737ca82ced)

another detail is that my ACR is in my "global" subscription and my ACA env is in my "non-prod" sub

what am I missing here?????
