### ISSUE TITLE
Bug: HTTP request returned status code 507: exceeded request buffer limit while retrying upstream

### ISSUE THREAD

**Issue by knobel-dk** [microsoft/azure-container-apps#1049]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Here is my deployment. Every so often the container app returns `HTTP request returned status code 507: exceeded request buffer limit while retrying upstream`.

```yaml
name: ...
type: Microsoft.App/containerApps
location: North Europe
properties:
  managedEnvironmentId: "..."
  environmentId: "..."
  workloadProfileName: Consumption
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: true
      targetPort: 5000
      transport: Auto
      traffic:
        - weight: 100
          latestRevision: true
      customDomains:
      allowInsecure: false
    secrets:
      - name: secretpassword
        value: ACR_PASSWORD
    registries:
      - server: REGISTRYSERVER
        username: ACR_USERNAME
        passwordSecretRef: secretpassword
  template:
    revisionSuffix: ''
    containers:
      - image: IMAGENAME
        name: CONTAINERNAME
        resources:
          cpu: 4
          memory: 8Gi
          ephemeralStorage: 8Gi
        probes:
          - type: Liveness
            httpGet:
              path: "/actuator/health"
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
    initContainers:
    scale:
      minReplicas: 1
      maxReplicas: 5
      rules:
        - name: cpu-over-sixty
          custom:
            type: cpu
            metadata:
              type: Utilization
              value: "60"
    volumes: []
    serviceBinds:
identity:
  type: None

```

### Steps to reproduce
1. Post a big-ish payload every so often

**Expected behavior** [What you expected to happen.]
I expect this request to reach my app

**Actual behavior** [What actually happened.]
The request i stopped before reaching my app

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
