### ISSUE TITLE
Severed bug: Consistently failed to pull image: 1/1 Pending:ImagePullBackOff on legion

### ISSUE THREAD

**Issue by ericxl** [microsoft/azure-container-apps#1056]
We ran into issues where Azure Container Apps constantly failed to pull images in us west 2 region. it has been a couple days now. 1/1 Pending:ImagePullBackOff on legion

This issue happen sporadically in a Consumption Workload profiles. For ACA with at least a sidecar, this happens around 70% of the time. For ACA with a single container, this happens around 20% of the time.
Container registry setup: we are using admin login. weird thing is if we use a public registry like in docker hub, this still happens.
We tried to create a new vnet and container app environment but issue still persists.

Is this known and when can we expect a fix? Please let me know how I could get more info

**Comment by maskati** [comment]
Possible fix https://github.com/microsoft/azure-container-apps/issues/960#issuecomment-1907375438

**Comment by chinadragon0515** [comment]
@ericxl can you please send us an email to acasupport at microsoft dot com with your containerapp, env info so we could follow up with you?

**Comment by JonasSamuelsson** [comment]
We are seeing the same issue. Should I contact you at acasupport as well @chinadragon0515 ?

**Comment by vinisoto** [comment]
Hi - we have identified a race condition as the root cause of the issue and are in the process of producing and rolling out a fix.

Details:

The root cause of the issue with users experiencing ImagePullBackoff errors is specifically a race condition within the platform impacting specifically apps running in the Consumption workload profile. This condition occurs when the system inaccurately updates the in-memory token, intended for image pulls, to an empty value for some replicas during the replica creation. 

Will update this issue once the rollout with the fix is completed.

**Comment by chinadragon0515** [comment]
The issue has been fixed and rolled out everywhere. close the issue.

**Comment by zlatanov** [comment]
@chinadragon0515 I am having this exact issue at the moment. No matter what I do, the container instance fails to pull the image. What do I need to do to resolve it?

**Comment by amalkyOneStone** [comment]
I am currently facing the same issue

**Comment by amalkyOneStone** [comment]
Has there been an update?

**Comment by amalkyOneStone** [comment]
> The issue has been fixed and rolled out everywhere. close the issue.

The issue hasn't been fixed yet

**Comment by kathy-lee** [comment]
I'm facing a similar issue in central-us region, when I was using the consumption plan, the container app was no problem, but since I need more memory(>4G), I switched to the dedicated plan with Consumption workload profile, then it was always failed in pull image.

**Comment by aurelien-boubennec** [comment]
Same issue since I rotated the keys in a container registry

**Comment by ajpogue** [comment]
@aurelien-boubennec   Please open a new case if you are still having an issue, referring back to this one.

**Comment by sangeethnandakumar** [comment]
I think this issue is not fixed yet as I'm getting this again.
Here are some details might be usefull:

### The first deployment is always success but future revisions often fails pulling
![Image](https://github.com/user-attachments/assets/dbc88138-be09-4891-81b9-612c9f563f58)

### Container Registry:
GitHub Packages (Private) => Pulled by ACA using provided PAT token

### Specific Error: (Seems like some protocol issue with Github)

![Image](https://github.com/user-attachments/assets/4a59be77-f46d-475d-bc23-cc82b661de95)

### Pipeline deploy stage:
![Image](https://github.com/user-attachments/assets/026a782d-a532-43ca-b19e-330cc606d700)

```yaml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Container Apps (Replace Existing Revision)
        uses: Azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.image_tag }}
          containerAppName: ${{ env.APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppEnvironment: ${{ env.ENVIRONMENT }}
          targetPort: 8080
          ingress: external
          registryUrl: ${{ env.REGISTRY }}
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GH_PAT_TOKEN }}
          environmentVariables: ENV_VAR_1=value1
```
