### ISSUE TITLE
Azure container apps not been able to attach Volume mount

### ISSUE THREAD

**Issue by hardiktessell** [microsoft/azure-container-apps#1062]
### Issue description

I am trying to run pulsar standalone at the same time attaching a volume mount at /pulsar/data but the container is continuously failing with persistent storage failure. 
I am following https://learn.microsoft.com/en-us/azure/container-apps/storage-mounts-azure-files?tabs=bash

```
LOCATION="eastus"

STORAGE_ACCOUNT_NAME="myacastorageaccount$RANDOM"
az storage account create \
  --resource-group $RESOURCE_GROUP \
  --name $STORAGE_ACCOUNT_NAME \
  --location "$LOCATION" \
  --kind StorageV2 \
  --sku Standard_LRS \
  --enable-large-file-share \
  --query provisioningState

STORAGE_SHARE_NAME="myfileshare"


az storage share-rm create \
  --resource-group $RESOURCE_GROUP \
  --storage-account $STORAGE_ACCOUNT_NAME \
  --name $STORAGE_SHARE_NAME \
  --quota 1024 \
  --output table

STORAGE_ACCOUNT_KEY=`az storage account keys list -n $STORAGE_ACCOUNT_NAME --query "[0].value" -o tsv`

STORAGE_MOUNT_NAME="mystoragemount"


az containerapp env storage set \
  --access-mode ReadWrite \
  --azure-file-account-name $STORAGE_ACCOUNT_NAME \
  --azure-file-account-key $STORAGE_ACCOUNT_KEY \
  --azure-file-share-name $STORAGE_SHARE_NAME \
  --storage-name $STORAGE_MOUNT_NAME \
  --name $ENVIRONMENT_NAME \
  --resource-group $RESOURCE_GROUP \
  --output table


CONTAINER_APP_NAME="pulsar-standalone"


az containerapp create \
  --name $CONTAINER_APP_NAME \
  --resource-group $RESOURCE_GROUP \
  --environment $ENVIRONMENT_NAME \
  --image apachepulsar/pulsar:3.1.0 \
  --min-replicas 1 \
  --max-replicas 1 \
  --target-port 6650 \
  --transport tcp \
  --ingress external \
  --query properties.configuration.ingress.fqdn


az containerapp show \
  --name $CONTAINER_APP_NAME \
  --resource-group $RESOURCE_GROUP \
  --output yaml > app.yaml 
```

after this i am updating app.yaml volumes with
```
  template:
    volumes:
    - name: myazurefilevolume
      storageName: mystoragemount
      storageType: AzureFile
      mountOptions: 'dir_mode=0777,file_mode=0777,uid=101,gid=101,mfsymlinks,nobrl'
    containers:
    - image: apachepulsar/pulsar:3.1.0
      name: pulsar-standalone
      command: ["bin/pulsar", "standalone", "--no-functions-worker"]
      volumeMounts:
      - volumeName: myazurefilevolume
        mountPath: /pulsar/data
      resources:
        cpu: 2
        ephemeralStorage: 4Gi
        memory: 4Gi
    initContainers: null
    revisionSuffix: ''
    scale:
      maxReplicas: 1
      minReplicas: 1
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
```

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Steps to reproduce
mentioned

**Expected behavior** [What you expected to happen.]
It should work attaching the volume mount

**Actual behavior** [What actually happened.]
persistent storage issue

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
facing this with both terraform and az cli

```[tasklist]
### Tasks
```
