### ISSUE TITLE
Unable to use variable in ADO pipeline azureSubscription

### ISSUE THREAD

**Issue by cwash05** [microsoft/azure-container-apps#1072]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I am unable to use a variable for the azureSubscription parameter in my ADO pipeline.  When used I get the following error.

"The pipeline is not valid. Job Deploy: Step AzureContainerApps input connectedServiceNameARM references service connection $(connectionName) which could not be found. The service connection does not exist, has been disabled or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

all of the other parameters using variables are okay
### Steps to reproduce
the pipeline code 

```yaml
stages:
    - stage: Deploy
    # dependsOn: Build
    # condition: succeeded()
    jobs:
    - job: Deploy
      strategy:
        matrix:
          chwashPipeline:
            buildinfo: $(chwashPipelineVar)
          # dkingPipeline:
          #   buildinfo: $(dkingPipelineVar)
      pool:
        # vmImage: 'ubuntu-latest'
        name: Default    
      steps:
      - task: PowerShell@2
        name: GetUserVariables
        inputs:
          targetType: 'inline'
          script: |
            $json = $env:BUILDINFO 
            $obj = ConvertFrom-Json -InputObject $json 
            $connectionName = $obj.connectionName 
            $containerAppName = $obj.containerAppName 
            $resourceGroup = $obj.resourceGroup 
            $name = $obj.name 
            
            Write-Host "Connection Name: $connectionName"
            Write-Host "Container App Name: $containerAppName"
            Write-Host "Resource Group: $resourceGroup"
            Write-Host "Name: $name"
        
            Write-Host "##vso[task.setvariable variable=connectionName]$connectionName"
            Write-Host "##vso[task.setvariable variable=containerAppName]$containerAppName"
            Write-Host "##vso[task.setvariable variable=resourceGroup]$resourceGroup"
            Write-Host "##vso[task.setvariable variable=name]$name"
            

      - task: AzureContainerApps@1
        displayName: 'ContainerAppDeploy-$(name)'
        inputs:
          appSourcePath: '$(Build.SourcesDirectory)'
          azureSubscription: '$(connectionName)'  
          acrName: 'akscbweb'
          containerAppName: '$(containerAppName)'
          resourceGroup: '$(resourceGroup)'
```

it only works when the azureSubscription value is hard coded.

**Expected behavior** [What you expected to happen.]
Expected that i would be able use a variable in the azureSubscription paremeter

**Actual behavior** [What actually happened.]
receive error above

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/23502916/6c7ec11b-a84b-42d5-a244-8920a9d9a20c)
