### ISSUE TITLE
Additional Port Mappings within Ingress Definition has no effect when using az containerapp update/create 

### ISSUE THREAD

**Issue by moelliDo** [microsoft/azure-container-apps#1073]
### This issue is a: (mark with an x)
- [x] bug report 
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When trying to update the ingress definition with `additionalPortMappings` using the Azure CLI, the changes have no effect on the container app. No additional tcp port mappings are created. 

### Steps to reproduce
1. create a `app.yaml` Deployment file and added `additionalPortMappings` as shown [here](https://learn.microsoft.com/de-de/azure/container-apps/ingress-how-to?pivots=azure-cli#use-additional-tcp-ports) and [here 
](https://github.com/microsoft/azure-container-apps/issues/891)
```yaml
...
properties:
  configuration:
    activeRevisionsMode: Single
    ingress:
      allowInsecure: false
      external: false
      targetPort: 8025
      transport: tcp
      additionalPortMappings:
        - external: false
          targetPort: 8125
          exposedPort: 8125
        - external: false
          targetPort: 8224
          exposedPort: 8224
    maxInactiveRevisions: null
...
``` 
2. updated containerapp/recreated containerapp using `az containerapp update --name "name" --resource-group "rg-name" --yaml app.yaml`

**Expected behavior** 
Container app should expose additionally added TCP ports

**Actual behavior** 
No additional TCP ports are exposed.

**Screenshots**         
![image](https://github.com/microsoft/azure-container-apps/assets/23486432/5747c8a6-bece-4865-ac01-900f2cfd6a0a)

### Additional context
This issue occurred using the azure CLI
