### ISSUE TITLE
Feature Request: App/Job Storage mount automation using Azure CLI

### ISSUE THREAD

**Issue by eladtpro** [microsoft/azure-container-apps#1153]
**Is your feature request related to a problem? Please describe**.  
Cannot use Azure CLI to mount volume to ACA app/job.
Use this guide as reference: [Use storage mounts in Azure Container Apps](https://learn.microsoft.com/en-us/azure/container-apps/storage-mounts?tabs=smb&pivots=azure-cli) 

**Describe the solution you'd like**.    
Ability to use one of the az containerapp commands for [app](https://learn.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest#az-containerapp-create)/[job](https://learn.microsoft.com/en-us/cli/azure/containerapp/job?view=azure-cli-latest#az-containerapp-job-create) instead of editing the yaml file:
```
az containerapp create/update
az containerapp job create/update
```
These are the pod original mounting attributes on the [yaml file](https://learn.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec?tabs=yaml):
```
  template:
    containers:
    - image: repo/testcontainerApp0:v1
      name: testcontainerApp0
      volumeMounts:
      - mountPath: "/myfiles"
        volumeName: azure-files-volume
    volumes:
    - name: azure-files-volume
      storageType: AzureFile
      storageName: myazurefiles
```

adding the following flags so it will represent the above volumes and volumeMounts entries: 
```
az containerapp job create --name myjob --resource-group myrg --volume-name azure-files-volume --volume-storage-type AzureFile --volume-storage-name myazurefiles --mount-path "/myfiles"
```

**Describe alternatives you've considered**.   
The alternative I found was to use ARM templates as shown in this guide:
[Use storage mounts in Azure Container Apps (ARM template)](https://learn.microsoft.com/en-us/azure/container-apps/storage-mounts?tabs=smb&pivots=azure-resource-manager)

Otherwise the only is manually exporting, editing, importing the yaml file.

**Additional context**.  
Microsoft guide for mounting Azure Files to container app/job "Use storage mounts in Azure Container Apps",
In this guide, when using Azure CLI you need to export the app/job yaml file, edit the yaml and then update the container app using az containerapp update --yaml job.yaml:
[Use storage mounts in Azure Container Apps](https://learn.microsoft.com/en-us/azure/container-apps/storage-mounts?tabs=smb&pivots=azure-cli)

More links:
[Azure Container Apps ARM and YAML template specifications](https://learn.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec?tabs=yaml)
[az containerapp create](https://learn.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest#az-containerapp-create)
[az containerapp job create](https://learn.microsoft.com/en-us/cli/azure/containerapp/job?view=azure-cli-latest#az-containerapp-job-create)
