### ISSUE TITLE
Configuration of custom readiness/liveness probes in ACA

### ISSUE THREAD

**Issue by timoknapp** [microsoft/azure-container-apps#118]
Hi there, 

is there a way of specifying a custom health check API for an Azure Container App? I am having issues with one of my applications since its secured by OAuth and therefore the simple probes to `<host>:<port>` fail by design with HTTP 401.

I am actually running a Spring Boot application which uses the health API under `<host>:<port>/actuator/health` which does not require any authentication. Is there any way of specifying this endpoint in either my `.bicep` file or in the portal?

Furthermore it would be really helpful to also define more detailed information like you can do with K8s

```
readinessProbe:
  tcpSocket:
     port: 8080
  initialDelaySeconds: <int>
  periodSeconds: <int>
livenessProbe:
  tcpSocket:
     port: 8080
  httpGet:
     path: /custom-path
     port: 8080
  initialDelaySeconds: <int>
  periodSeconds: <int>
```

Here is a sample log statement from the Azure Portal:
![image](https://user-images.githubusercontent.com/11437666/154806809-9c6c0e95-d423-4fe4-aeb8-3d3f31a2b1ce.png)

I was also looking for the source code of the `probe-shim` container performing the probes, but it seems that its not open source.

Any help or best practice will be highly appreciated!

Regards
Timo
