### ISSUE TITLE
Configuration to restrict incoming traffic only from Azure FrontDoor

### ISSUE THREAD

**Issue by GrillPhil** [microsoft/azure-container-apps#120]
Allow to configure a restriction to allow external ingress only from Azure FrontDoor similar to ipRestrictions in Azure App Service. Ideally this could be configured in as part of the ingress configuration in the container app's ARM template like so:

```yaml
resource containerApp 'Microsoft.Web/containerApps@2022-02-22-preview' = {
  properties: {
    configuration: {
      ingress: {
        external: true
        ipSecurityRestrictions: [
          {
            ipAddress: 'AzureFrontDoor.Backend'
            tag: 'ServiceTag'
            action: 'Allow'
            priority: 100
            name: 'Frontdoor'
            headers: {
              'x-azure-fdid': [
                frontDoorId
              ]
            }
          }
        ]     
      }      
    }
  }
}
```
