### ISSUE TITLE
[KEDA][AzureEventHub] App not scaling to zero

### ISSUE THREAD

**Issue by goncalo-oliveira** [microsoft/azure-container-apps#1225]
### This issue is a:
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have set up a container app with 0 - 4 replicas, using `azure-eventhub` scale rule with the following settings

```yaml
- type:
  metadata:
    activationUnprocessedEventThreshold: 10
    checkpointStrategy: blobMetadata
    blobContainer: ...
    connectionFromEnv: ...
    consumerGroup: ...
    eventHubNameFromEnv: ...
    storageConnectionFromEnv: ...
    unprocessedEventThreshold: 64
```

I did have an earlier issue, which I commented on #972, where the app didn't scale down, but that was down to the missing `checkpointStrategy` which was updated. It now scales up and down to 1, depending on the load. However, it does not scale down to zero when there are no events to process.

I was thinking that it might be intended behaviour, but from the documentation, it seems that it should scale to zero and activate at a threshold

> **activationUnprocessedEventThreshold** - Target value for activating the scaler. Learn more about activation [here](https://keda.sh/docs/2.14/concepts/scaling-deployments/#activating-and-scaling-thresholds).

### Steps to reproduce
1. Set up container app with `minReplicas: 0` and a positive `maxReplicas` value
2. Set up scale rules as described above
3. Maintain a period without event intake

**Expected behavior**

Without any events being sent to the Event Hub, the expectation was for the app to scale to zero. When the unprocessed messages hits the `activationUnprocessedEventThreshold`, the app scales back to 1.

**Actual behavior**

Without any events being sent to the Event Hub, the number of replicas is kept at `1`.

**Screenshots**         

<img width="825" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/2210485/87309796-c6b0-47c5-b53b-0f0817320dba">
<img width="427" alt="image" src="https://github.com/microsoft/azure-container-apps/assets/2210485/5e45f8c4-ea5b-45e4-a057-d7d392a8e82d">
