### ISSUE TITLE
Revision restart required when minimum replicas = 1

### ISSUE THREAD

**Issue by damiangelis** [microsoft/azure-container-apps#1244]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

I have a container app with single-revision mode, and minimum replicas set to 1:

<img width="1065" alt="image" src="https://github.com/user-attachments/assets/46bd3a9a-f587-4f35-af22-7b4772d3ff1d">

<img width="580" alt="image" src="https://github.com/user-attachments/assets/7ef36b4b-2933-4b31-bcf5-5bd01fe97812">

These are the steps of my Azure pipeline to deploy new changes to the app:

```yaml
- script: |
  docker login $(ACR_LOGIN_SERVER) -u $(ACR_USERNAME) -p $(ACR_PASSWORD)
displayName: "Login to Azure Container Registry"

- script: |
  docker build . --no-cache --file Dockerfile -t $(ACR_LOGIN_SERVER)/$(ACR_QUERY_REPOSITORY_NAME):$(Build.SourceVersion)
workingDirectory: ./backend/server
displayName: "Build Docker image"

- script: |
  docker push $(ACR_LOGIN_SERVER)/$(ACR_QUERY_REPOSITORY_NAME):$(Build.SourceVersion)
displayName: "Push image to Azure Container Registry"

- script: |
  docker tag $(ACR_LOGIN_SERVER)/$(ACR_QUERY_REPOSITORY_NAME):$(Build.SourceVersion) $(ACR_LOGIN_SERVER)/$(ACR_QUERY_REPOSITORY_NAME):latest
  docker push $(ACR_LOGIN_SERVER)/$(ACR_QUERY_REPOSITORY_NAME):latest
displayName: "Tag and push latest image to Azure Container Registry"

- task: AzureCLI@2
inputs:
  azureSubscription: $(ARM_SUBSCRIPTION_ID)
  scriptType: bash
  scriptLocation: inlineScript
  inlineScript: |
    az containerapp up --name $(CONTAINER_APP_NAME) --resource-group $(RESOURCE_GROUP_NAME) --image $(ACR_LOGIN_SERVER)/$(ACR_QUERY_REPOSITORY_NAME):latest
displayName: "Deploy image to container app"

- task: AzureCLI@2
inputs:
  azureSubscription: $(ARM_SUBSCRIPTION_ID)
  scriptType: bash
  scriptLocation: inlineScript
  inlineScript: |
    revisions=$(az containerapp revision list --name $(CONTAINER_APP_NAME) --resource-group $(RESOURCE_GROUP_NAME) | jq -r '.[0].name')
    az containerapp revision restart --revision $revisions --resource-group $(RESOURCE_GROUP_NAME)
displayName: "Restart container app revision to renew replica"
```

After setting minimum replicas to 1, I have to add a step at the end to restart the revision, which will renew the replica. Otherwise, the new deployed changes won't take effect. Do I really need to add this step? Am I doing something wrong?
