### ISSUE TITLE
AZ CLI: az containerapp update fails due to 'Microsoft.Web' namespace.

### ISSUE THREAD

**Issue by willvelida** [microsoft/azure-container-apps#127]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] regression (a behavior that used to work and stopped in a new release)

### Issue description

I'm attempting to update the image that my Container App is using via the AZ CLI command ```az containerapp update```. This is executed in the following workflow file like so:

```yaml
- name: 'Deploy Container App'
      uses: Azure/cli@v1
      with:
        inlineScript: |
          echo "Installing containerapp extension"
          az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
          echo "Starting Deploying"
          az containerapp update -n velidabookstoreapi -g todocontainerapp-rg -i ${{ secrets.REGISTRY_LOGIN_SERVER }}/bookstoreapi:${{ github.sha }} --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} --registry-username  ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --debug

```

This step completed successfully when Container Apps were in the ```Microsoft.Web``` namespace. But since the migration to ```Microsoft.Apps``` namespace (#109), the command now fails.

### Steps to reproduce
1. .. Create a new Azure Container App via the Portal with your own image
2. .. Attempt to update the image using the AZ command az containerapp update as shown in this [workflow file](https://github.com/willvelida/bookstore-containerapps/blob/main/.github/workflows/deployContainer.yml).

**Expected behavior** [What you expected to happen.]

The container image is deployed to my Container App successfully.

**Actual behavior** [What actually happened.]

The AZ CLI command fails and produces the following error:

```json
{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Web/containerApps/velidabookstoreapi' under resource group 'todocontainerapp-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
```

### Additional context

My GitHub Action workflow executes the following command before updating my container app:

```yaml
az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
```

Has the extension file been updated? If so, is this the cause of the error?

I have registered the ```Microsoft.App``` namespace in my subscription
