### ISSUE TITLE
az containerapp create with Dapr: --dapr-components must be an array

### ISSUE THREAD

**Issue by ChrisProlls** [microsoft/azure-container-apps#128]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When trying to use `az containerapp create` with Dapr enabled and `--dapr-components` option following [this](https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=bash#set-up-a-state-store) tuto, the CLI complains about the option that need to be an array.

### Steps to reproduct
1. Follow the tutorial
2. Use this command
```
az containerapp create \
  --name nodeapp \
  --resource-group $RESOURCE_GROUP \
  --environment $CONTAINERAPPS_ENVIRONMENT \
  --image dapriosamples/hello-k8s-node:latest \
  --target-port 3000 \
  --ingress 'external' \
  --min-replicas 1 \
  --max-replicas 1 \
  --enable-dapr \
  --dapr-app-port 3000 \
  --dapr-app-id nodeapp \
  --secrets "storage-account-name=${STORAGE_ACCOUNT},storage-account-key=${STORAGE_ACCOUNT_KEY}" \
  --dapr-components ./components.yaml
```

**Expected behavior** [What you expected to happen.]
Conatainer App should be created.

**Actual behavior** [What actually happened.]
The CLI complains about the `--dapr-components` option that should be an option.
Exact error : `--dapr-components: must be an array of dapr component(s)`

**Screenshots**         
![image](https://user-images.githubusercontent.com/1511666/156770703-54abdb9e-e8a8-44bc-b865-8fbc6c6eb78a.png)

### Additional context
Using the CLI into Bash with Visual Studio Code.

**Comment by ChrisProlls** [comment]
Closing this as I've found how to use the option correctly.
The option should be used in correlation with the `--secrets` command and this file (as an example if you have multiple Dapr configuration)

```yaml
- name: dapr-store
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      secretRef: redis-host
    - name: redisPassword
      secretRef: redis-password
    - name: actorStateStore
      value: "true"

- name: dapr-pubsub
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString 
      secretRef: servicebus-connectionstring
```

The `component.yaml` (the file above) is another file only used for Container Apps deployment, you cannot re-use existing Dapr configuration files.
