### ISSUE TITLE
GitHub Actions doesn't properly deploy the Ingress on Container Apps 

### ISSUE THREAD

**Issue by hartou** [microsoft/azure-container-apps#1285]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I use the Actions below to the deploy the container apps and does not work as expected:
1. Ingress is unavailable
2. Deployment fails 

Here is the actions:
```yml
    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        imageToDeploy: ${{ secrets.containerRegistryName }}.azurecr.io/saworkssite:latest
        containerAppName: saworkssite
        resourceGroup: fineractdev-rg
        containerAppEnvironment: fineractdev-aca-env
        targetPort: 80
        ingress: external
``` 

### Steps to reproduce
1. Create a GitHub Actions
4. add the actions above

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
