### ISSUE TITLE
`az containerapp create` causes downtime in single revision mode

### ISSUE THREAD

**Issue by chinwobble** [microsoft/azure-container-apps#1305]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I am deploying an Azure Container App in single revision mode.
I define how I want the app to work with healthchecks in yaml and I use yq to change the image tag when I want to release a new version.
When I deploy the new app using `az containerapp create` I get 503s for a minute (I think while the new pod) is being made ready.

### Steps to reproduce
1. . 
Create a yaml file 
```yaml
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? /subscriptions/{subscriptionId}/resourcegroups/p-rg-platform-shared/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-acrpull
    : {}
location: Australia East
properties:
  configuration:
    activeRevisionsMode: Single
    ingress:
      allowInsecure: false
      clientCertificateMode: null
      corsPolicy: null
      exposedPort: 0
      external: true
      ipSecurityRestrictions: null
      stickySessions: null
      targetPort: 8080
      traffic:
        - latestRevision: true
          weight: 100
      transport: Auto
    maxInactiveRevisions: null
    service: null
    registries:
      - identity: '/subscriptions/{subscriptionId}/resourcegroups/p-rg-platform-shared/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-acrpull'
        server: acrcsd.azurecr.io
  template:
    containers:
      - image: mycompany.azurecr.io/tools-app:1
        name: app
        resources:
          cpu: 0.25
          ephemeralStorage: 1Gi
          memory: 0.5Gi
        env:
          - name: DOTNET_ENVIRONMENT
            value: Staging
    initContainers: null
    revisionSuffix: ''
    scale:
      maxReplicas: 1
      minReplicas: 1
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes: null
tags:
  env: staging
```
2. Run the following command to deploy the yaml file
```bash
az containerapp create \
    --name $appname \
   --resource-group $RESOURCE_GROUP \
    --environment "$managedEnvId" \
    --subscription $SUBSCRIPTION_ID \
    --yaml $transformed_yaml
```
3. Deploy a new version of your code with a new image tag.
```
docker push mycompany.azurecr.io/tools-app:2
```
4. Update the yaml file above with the image tag. We use `sed` in a bash script to read the value from a pipeline_run_id.
5. There is downtime

**Expected behavior** [What you expected to happen.]
According to this page there is zero downtime
https://learn.microsoft.com/en-us/azure/container-apps/revisions#zero-downtime-deployment

**Actual behavior** [What actually happened.]
We get 503 error for a few seconds after `az containerapp create` has been run.
I think this is the error message from envoy which is used internally by ACA.
```
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: remote connection failure, transport failure reason: delayed connect error: 111
```

**Screenshots**         

### Additional context
- my app environment is in a custom VNET
- Using azure cli
