### ISSUE TITLE
Container App Jobs - Self-hosted Action Runners run, but dont pick up Workflows in ACA

### ISSUE THREAD

**Issue by tomtreffke** [microsoft/azure-container-apps#1354]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ x ] bug report -> please search issues before submitting
- [ x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

**### Issue description**

According to the [MSFT Tutorial: Self-Hosting GitHub Runners in Container Apps Jobs](https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=bash&pivots=container-apps-jobs-self-hosted-ci-cd-github-actions) the process is pretty straight forward. 
In my case, the Deployment of the Container App Job succeeds, however Workflow Runs in GitHub stay in Queue and are not being picked up.

I used different Container Images of the Github Action Runner Build from ghcr.io - 2.321.0, 2.320.0, 2.319.0, 2.318.0

Container Apps Environment looks like this:
Environment type - Consumption only
Applications : 3
KEDA version : 2.15.1
Dapr version : 1.12.5
.NET Aspire Dashboard : enable

Logs:
```
az containerapp job logs show -g ccacs-devops-rg -n devops-gh-caj --container gh-runner --follow --format text

Command group 'containerapp job logs' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus

No execution provided, defaulting to latest execution: devops-gh-caj-xrws5
No replica provided, defaulting to latest replica: devops-gh-caj-xrws5-6lwlx
2024-11-28T12:04:36.31839  Connecting to the container 'gh-runner'...
2024-11-28T12:04:36.34705  Successfully Connected to container: 'gh-runner' [Execution: 'devops-gh-caj-xrws5', Replica: `'devops-gh-caj-xrws5-6lwlx']



```
![Image](https://github.com/user-attachments/assets/d904112e-f072-4204-9139-5946a58a71b2)

### Steps to reproduce
-

**Expected behavior** [What you expected to happen.]
Container App Jobs not only run, but they also pick up workflow runs from GH.

**Actual behavior** [What actually happened.]
#Container App Jobs Run, but dont pick up Workflow runs from Github

**Screenshots** 
[Link to Repo + Workflow Runs](https://github.com/meowmentum/gh-sh-runner/actions/workflows/test-runner.yml)

![Image](https://github.com/user-attachments/assets/bd521596-50ec-4a4f-842d-0fd11bc942d1)

![Image](https://github.com/user-attachments/assets/92cdf0f6-decb-4085-b859-287227fc6dba)

### Additional context
The Action Runner runs without any issues on all of above mentioned container images if I use Podman locally:
```podman run -it -e GITHUB_PAT=<1234> -e GH_URL=<REPO-URL> -e REGISTRATION_TOKEN_API_URL=<REG-TOKEN-API-UR> ghcr.io/actions/actions-runner:2.321.0

./config.sh --pat $GITHUB_PAT --url $GH_URL --unattended && ./run.sh

```

so the question i have is: since i used the exact same GH URL and PAT for both the locally run agent and the Container App Job, and used the exact commands from the Tutorial, what could possibly cause this? The Container App Job ocassionaly logging that it pulls images and creates containers, but thats pretty much it.

**Comment by tomtreffke** [comment]
I found the issue after digging around with an AKS Cluster + KEDA deployment.

The Github Runner container images published under ghcr.io/actions/actions-runner do not come with an Entrypoint defined. 
[Link](https://github.com/actions/runner/blob/v2.321.0/images/Dockerfile)

In the Tutorial, [the build to Azure Container Registry](https://learn.microsoft.com/en-us/azure/container-apps/tutorial-ci-cd-runners-jobs?tabs=bash&pivots=container-apps-jobs-self-hosted-ci-cd-github-actions#build-the-github-actions-runner-container-image) refers to a seperate Github Repo which I kindly disregarded - the Docker image file there includes the entrypoint - which is for both Azure DevOps Runners and GitHub Action Runners Shell scripts to load the URL and PAT from Environment Variables and init the Action Runner afterwards. [Link](https://github.com/Azure-Samples/container-apps-ci-cd-runner-tutorial/blob/main/github-actions-runner/entrypoint.sh#L3)

In the KEDA Deployment on AKS I managed to use the GitHub Runner Images with command override:

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: scaledjob-github-runner
  namespace: keda
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: scaledjob-github-runner
      spec:
        containers:
        - name: scaledjob-github-runner
          image: ghcr.io/actions/actions-runner:2.321.0
          command: [ "/bin/bash" ]
          args: [ "-c", "./config.sh --unattended --url $GH_URL --pat $GITHUB_PAT && ./run.sh" ]
          imagePullPolicy: Always
          env:
          - name: EPHEMERAL
            value: "true"
          - name: DISABLE_RUNNER_UPDATE
            value: "true"
          - name: GH_URL
            value: "https://github.com/<org>/<repo>"
          - name: RUNNER_SCOPE
            value: "repo"
          - name: LABELS
            value: "self-hosted"
          - name: GITHUB_PAT
            valueFrom:
              secretKeyRef:
                name: github-auth
                key: personalAccessToken
          - name: REGISTRATION_TOKEN_API_URL
            value: "https://api.github.com/repos/<org>/<repo>/actions/runners/registration-token"
        restartPolicy: Never
  minReplicaCount: 0
  maxReplicaCount: 20
  pollingInterval: 30
  triggers:
  - type: github-runner
    metadata:
      githubApiURL: "https://api.github.com"
      repository: https://github.com/<org>/<repo>
      accessToken: github-auth
      accessTokenKey: personalAccessToken
      labels: self-hosted
      targetWorkflowQueueLength: "1"
      runnerScope: repo
      owner: <org>
      repos: <repos>
    authenticationRef:
      name: github-trigger-auth
```


I haven't managed to get the ContainerApps Job running with Command Override yet, but since the Tutorial (indirectly) lets you bild your own runner image, this issue can be closed.

classic RTM
