### ISSUE TITLE
Feature Request: Multiple key/values per secret from key vault

### ISSUE THREAD

**Issue by AurimasNav** [microsoft/azure-container-apps#1400]
**Is your feature request related to a problem? Please describe**.  
Currently for every "key=value" to use as a secret you need to create a separate entry in key vault and create individual secret objects for container app for each such entry, this is very tedious for apps that have 50 env variables which we would like to treat as secrets.

**Describe the solution you'd like**.    
In kubernetes it is common practice to have multiple key/values per secret

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: some-secret
type: opaque
data:
  auth-extra-groups: c3lzdGVtOmJvb3RzdHJhcHBlcnM6a3ViZWFkbTpkZWZhdWx0LW5vZGUtdG9rZW4=
  expiration: MjAyMC0wOS0xM1QwNDozOToxMFo=
  token-id: NWVtaXRq
  token-secret: a3E0Z2lodnN6emduMXAwcg==
```

 and the whole secret can be mounted as `envFrom` object, I would like those capabilities on container apps.

1. Create key vault entry with json value

```json
{
 "auth-extra-groups": "system:bootstrappers:kubeadm:default-node-token"
  "expiration": "2020-09-13T04:39:10Z"
  "token-id": "5emitj"
  "token-secret": "kq4gihvszzgn1p0r|
}
```

2. create container app secret referencing that key vault entry and specifying that it should be "extracted from json"
3. specify that this secret should be mounted to container app env
4. as a result we should have following entries added to container environment:

```shell
 auth-extra-groups=system:bootstrappers:kubeadm:default-node-token
 expiration=2020-09-13T04:39:10Z
 token-id=5emitj
 token-secret=kq4gihvszzgn1p0r|
```

**Describe alternatives you've considered**.   
Currently I'm using these "json" secrets in key vault and create env vars from them via tofu/terrafom, but it is not ideal as that leaves env vars values visible via container app gui instead of having key vault references there. Also if secret in key vault is updated, I need to apply infra as code configuration for those values to be re-read and updated for container apps.

**Additional context**.  
This seems like a very common use scenario for secrets in kubernetes so maybe this is already possible in container apps, I just didn't see how? Any tips appreciated.
