### ISSUE TITLE
invalid or missing template.dapr.components.scopes calling az containerapp create with Dapr enabled

### ISSUE THREAD

**Issue by markheath** [microsoft/azure-container-apps#147]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

I am getting the following error message when attempting to use the Azure CLI to call `az containerapp create`:

```
The following field(s) are either invalid or missing. Required value: template.dapr.components.scopes.
````

I have been attempting to follow the steps in the [tutorial documentation](https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=powershell), but even with my components.yaml exactly matching the example from the tutorial, I still get this error. 

Here's the command I'm running 

```
az containerapp create `
  --name nodeapp `
  --resource-group $RESOURCE_GROUP `
  --environment $CONTAINERAPPS_ENVIRONMENT `
  --image dapriosamples/hello-k8s-node:latest `
  --target-port 3000 `
  --ingress 'external' `
  --min-replicas 1 `
  --max-replicas 1 `
  --enable-dapr `
  --dapr-app-port 3000 `
  --dapr-app-id nodeapp `
  --secrets "storage-account-name=${STORAGE_ACCOUNT},storage-account-key=${STORAGE_ACCOUNT_KEY}" `
  --dapr-components ./dapr/containerapps-components/components.yaml
```

Components.yaml:
```
- name: statestore
  type: state.azure.blobstorage
  version: v1
  metadata:
  - name: accountName
    secretRef: storage-account-name
  - name: accountKey
    secretRef: storage-account-key
  - name: containerName
    value: statestore
```

I've tried various ways of adding scopes to the `components.yaml` but without success

I am using Azure CLI v2.34.1 with the containerapp extension version 0.2.4
