### ISSUE TITLE
Generated Github Action Workflow Includes Incorrect Paths Filter

### ISSUE THREAD

**Issue by davidtucker** [microsoft/azure-container-apps#174]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
The current generated GitHub actions workflow uses a paths filter that is not matching what it intends to match:

```
name: Trigger auto deployment for containerapps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - './**'
```

It appears as if this path filter `./**` is intended to match anything, but based on the way that GitHub evaluates the paths, this won't match anything ([see docs](https://docs.github.com/en/enterprise-server@3.4/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)).  

I'm not sure if this is an edge case based on how I configured my Container App within Azure.

### Steps to reproduce
1. Add continuous deployment to a Container App.
2. See the generated Yaml file include the path filter listed above.
3. Commits will NOT trigger the workflow unless this path filter is removed.

### Additional context
This work was all done in the portal.

**Comment by kendallroden** [comment]
We are fixing defects in the CI/CD workflow. Thanks for reporting

**Comment by xwang971** [comment]
Hi @davidtucker. Sorry for the inconvenience. The fix is already in. Could you please check if it works as expected?

**Comment by davidtucker** [comment]
I am currently unable to confirm due to #187 .  I haven't tried with the CLI, but I can check that later today (I was preparing a demo that would leverage the portal).

**Comment by davidtucker** [comment]
With the fix to #187, I can verify that this is now fixed.  Here is the now generated path filters:

```
name: Trigger auto deployment for containerapp xxxxxxx

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ start ]
    paths:
    - '**'
    - '.github/workflows/xxxxxxx-AutoDeployTrigger-245f5aec-9dbc-4825-a36b-6119f8d76be4.yml'
...
```
