### ISSUE TITLE
Feature Request: Expose OpenTelemetry Collector configuration

### ISSUE THREAD

**Issue by denniszielke** [microsoft/azure-container-apps#208]
**Is your feature request related to a problem? Please describe**.  
I want to use my own observability solution and not azure monitor. To connect I need the ability to configure my own otel processors and exporters.

**Describe the solution you'd like**.    
I would like the ability to configure receivers, processors, (extensions?) and exporters.

**Describe alternatives you've considered**.   
The alternative would be to run my own otel collector as ACA service and manually change all other ACA apps to use them. This does not seem like a scalable good idea.

**Additional context**.

**Comment by kendallroden** [comment]
Thanks for this. It is a consideration moving forward definitely

**Comment by denniszielke** [comment]
@JennyLawrance yes that is what we are doing today but on the long run this does not scale (we need to maintain the same config , we need to make sure every dev creates the right config for each microservice and this is not what a PaaS should enforce). Also the performance overhead is significant as long ACA is limited to 4GB in total.

**Comment by edeandrea** [comment]
Adding onto this (& tagging @agoncal as well) - If I wanted to run an OTel collector instance as its own containerapp its currently very difficult to inject the configuration, since ContainerApps does not expose a ConfigMap.

For example, if I wanted to run the Otel collector on kubernetes, I could just deploy this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    system: quarkus-super-heroes
    app: otel-collector
    role: monitoring
data:
  otel-collector-config.yml: |2
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      jaeger:
        endpoint: jaeger:14250
        tls:
          insecure: true

    processors:
      batch:

    extensions:
      health_check:

    service:
      extensions:
        - health_check
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    system: quarkus-super-heroes
    name: otel-collector
    app: otel-collector
    role: monitoring
    app.kubernetes.io/part-of: monitoring
    app.openshift.io/runtime: opentelemetry
  annotations:
    app.openshift.io/connects-to: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      name: otel-collector
  template:
    metadata:
      labels:
        name: otel-collector
        app: otel-collector
        role: monitoring
    spec:
      containers:
        - image: otel/opentelemetry-collector:0.53.0
          name: otel-collector
          args:
            - "--config=/conf/otel-collector-config.yml"
          ports:
            - name: health-check
              containerPort: 13133
            - name: otlp-receiver
              containerPort: 4317
          volumeMounts:
            - name: otel-collector-config
              mountPath: /conf
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 32Mi
          livenessProbe:
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: health-check
              scheme: HTTP
              path: /
          readinessProbe:
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: health-check
              scheme: HTTP
              path: /
          startupProbe:
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              port: health-check
              scheme: HTTP
              path: /
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector-config
```

I haven't yet found a good way to do this in Azure ContainerApps. I found https://docs.microsoft.com/en-us/azure/container-apps/storage-mounts?pivots=aca-cli#azure-files but that means I have to maintain a separate yaml file specific to azure containerapps, which contains most of the same fields as a kubernetes yaml. That doesn't seem like a scalable solution, especially if all my CI/CD automation uses the `az` cli.
