### ISSUE TITLE
Feature Request: improved DX around dapr components schema / bicep (pubsub)

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/azure-container-apps#271]
**Is your feature request related to a problem? Please describe**.  

[According to the docs](https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr-azure-resource-manager?tabs=bash&pivots=container-apps-bicep#set-up-a-state-store):

> Container Apps does not currently support the native [Dapr components schema](https://docs.dapr.io/operations/components/component-schema/). 

The docs in question feature an example containing some Bicep which tackles creating dapr components in Azure Container Apps.  However it's the only example I've happened upon and it's kind of unclear how best to tackle Dapr components generally when it comes to Azure Container Apps. How does one translate something like this:

```yml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: weather-forecast-pub-sub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""
scopes:
- node-app
- dotnet-app
```

into Bicep that will correctly implement the required dapr components in ACAs?

I've been able to ignore the existence of dapr components for simple service invocation style applications. However that's not possible when trying to implement an app using the pubsub mechanism. However, I've been unable to find any examples of using dapr pubsub with Azure Container Apps.

**Describe the solution you'd like**.    

It would be tremendous to either have:
- native support in Azure Container Apps for the Dapr components schema **or** 
- clear guidance on how to use Bicep to deploy Dapr components

**Describe alternatives you've considered**.   

N/A

**Additional context**.  

I've been (very slowly) writing a blog post on how to use pubsub in Azure Container Apps with dapr.  The draft (far from complete) is here: https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/193

More usefully, the code that the blog post demonstrates can be found here:
https://github.com/johnnyreilly/dapr-devcontainer-debug-and-deploy/tree/pubsub (including a devcontainer to run in)

It works well locally (using native dapr components) but I'm rather at a loss as to how to take it that final stage to deployment, due to my lack of clarity around how to tackle dapr components in Azure Container Apps.

BTW I'm highly motivated to use ACAs and I'd be happy to provide more feedback.

## Update: 19/06/2022

@masters3d shared [this pointer](https://discord.com/channels/938116342538706975/938116343289511988/987793817707118642) in the discord which pointed me to the pubsub Bicep example here: https://github.com/Azure/reddog-containerapps/blob/main/deploy/bicep/modules/dapr-components/pubsub.bicep

This is great; I've managed to copy it into my repo: https://github.com/johnnyreilly/dapr-devcontainer-debug-and-deploy/pull/3/commits/dee199abfb652f9fc9f88eb7fbff4b0bc721121b

It deploys successfully which is great. It looks like it works: https://main-web.proudwave-1d35da7d.northeurope.azurecontainerapps.io/

![sending email](https://user-images.githubusercontent.com/1010525/174468391-685e5ae8-02bb-49ba-9483-612f36cc2d4e.gif)

![screenshot of subscription in azure portal](https://user-images.githubusercontent.com/1010525/174468544-288b4625-50c1-4d18-9742-cc24389dab20.png)

However a problem remains: how can we configure subscriptions via Bicep; like so:

```yml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: weather-forecast-pub-sub
spec:
  topic: weather-forecasts
  route: /SendWeatherForecast
  pubsubname: weather-forecast-pub-sub
scopes:
- node-app
- dotnet-app
```

We've got the "pub" part of pubsub working, but not the "sub" yet :smile: 

Is there any information around how to configure subscriptions with Bicep?

It looks like declarative subscriptions may not be supported yet:

https://docs.microsoft.com/en-us/azure/container-apps/dapr-overview?tabs=bicep1%2Cyaml#known-limitations

However, the examples for C# programmatic subscriptions do not appear to be valid: https://github.com/dapr/docs/issues/2538

## Update 20/06/2022

I couldn't get programmatic subscriptions working using the docs, but there is a way using the .NET minimal API approach. Documented here:

https://blog.johnnyreilly.com/2022/06/21/azure-container-apps-pubsub
