### ISSUE TITLE
Feature Request: GitHub Actions using GitHub Container Registry

### ISSUE THREAD

**Issue by asashiho** [microsoft/azure-container-apps#332]
**Is your feature request related to a problem? Please describe**.  
I want to create a workflow using the GitHub Container registry in Container Apps.
First, we registered the following GitHub Actions:

```bash
az containerapp github-action add \
  --repo-url "https://github.com/xxx/xxx" \
  --branch main \
  -n sample \
  -g sample-rg \
  --registry-url ghcr.io \
  --registry-username xxx \
  --registry-password xxx \
```

But, an error occurs that the Path of the container image does not exist.
```yaml
        with:
          push: true
          tags: ghcr.io/sample:${{ github.sha }}
          file: ./Dockerfile
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build
    ...
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
    ...
            az containerapp update -n sample -g sample-rg --image ghcr.io/sample:${{ github.sha }}
```

**Describe alternatives you've considered**.   
It works when I update the workflow. Is this correct?

* before

```yaml
tags: ghcr.io/sample:${{ github.sha }}
az containerapp update -n sample -g sample-rg --image ghcr.io/sample:${{ github.sha }}
```

* after

```yaml
tags: ghcr.io/${{ github.repository_owner }}/sample:${{ github.sha }}
az containerapp update -n sample -g sample-rg --image ghcr.io/${{ github.repository_owner }}/sample:${{ github.sha }}
```
