### ISSUE TITLE
Container App Deployment

### ISSUE THREAD

**Issue by mswilson4040** [microsoft/azure-container-apps#337]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I am working building a pipeline in Azure DevOps to deploy a container app. Deployment to the Azure Container Registry works flawlessly but I am having issues with creating/updating the revision to reflect the new container

### Steps to reproduct
1. Deploy docker image to azure container registry
2. Using the `az containerapps create` command, create a revision.
3. Observe that you get the UNAUTHORIZED error

**Expected behavior** [What you expected to happen.]
Revision is updated/created

**Actual behavior** [What actually happened.]
Release pipeline fails with UNAUTHORIZED error

**Screenshots**         

> 2022-08-02T18:40:14.0446365Z [command]/usr/bin/bash /home/vsts/work/_temp/azureclitaskscript1659465610495.sh 20299
> 2022-08-02T18:40:14.1986217Z WARNING: Command group 'config' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
> 2022-08-02T18:40:15.8944558Z WARNING: The command requires the extension containerapp. It will be installed first.
> 2022-08-02T18:40:30.3230598Z WARNING: The installed extension 'containerapp' is in preview.
> 2022-08-02T18:40:33.3084057Z ERROR: The following field(s) are either invalid or missing. Invalid value: "myacr.azurecr.io/activities-api:20299": GET https:?scope=repository%3Aactivities-api%3Apull&service=myacr.azurecr.io: UNAUTHORIZED: authentication required, visit https://aka.ms/acr/authorization for more information.: template.containers.activities-api.image.

Command being ran:
```
az config set extension.use_dynamic_install=yes_without_prompt

az containerapp create -n activities-api -g activity-service \
    --image myacr.azurecr.io/activities-api:$1 --environment activity-service \
    --ingress external --target-port 80 
```

### Additional context
The same command produces the same error within the Release Pipeline, and locally.

I am running a similar command in another Realese pipeline that should go through the same authentication process, but it works as expected. That command is this:

`az acr import --name myCompany --source myacr.azurecr.io/myCompany-stem-dev:$(Release.Artifacts._myCompany.Stem.BuildId) -t myCompany-stem:latest -t myCompany-stem:$(Release.Artifacts._myCompany.Stem.BuildId) --force`

A couple of questions:
1. What needs to be in place for the container apps to successfully pull an image from the Azure Container Registry?
2. Is the `az cli` the correct path to take when wanting continuous deployment to container apps?
3. Is there any "native" tasks in the roadmap for Azure DevOps that make it a little easier to work with (not using the CLI commands directly)?

**Comment by mswilson4040** [comment]
After changing my command to have the appended `--registry-server myAcr.azurecr.io`, it worked like a charm. So I think my original question is about an issue between the chair and keyboard.

I would like to get some direction/guidance on what is recommended for deploying Container Apps using Azure DevOps, however.

**Comment by anthonychu** [comment]
The exact pipeline will vary but here's an example. We're working on adding documentation on how to set up a DevOps pipeline.

```yaml
trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build

  jobs:
  - job: build
    displayName: Build app

    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'myreg-service-connection-name'
        repository: 'hello-aca'
        command: 'buildAndPush'
        Dockerfile: 'hello-container-apps/Dockerfile'
        tags: '$(Build.BuildId)'

- stage: Deploy

  jobs:
  - job: deploy
    displayName: Deploy app

    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'my-subscription-service-connection-name'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # automatically install Container Apps CLI extension
          az config set extension.use_dynamic_install=yes_without_prompt

          # ensure registry is configured in container app
          az containerapp registry set \
            --name hello-aca \
            --resource-group mygroup \
            --server myreg.azurecr.io \
            --identity system

          # update container app
          az containerapp update \
            --name hello-aca \
            --resource-group mygroup \
            --image myreg.azurecr.io/hello-aca:$(Build.BuildId)
```
