### ISSUE TITLE
Deploying container app with private docker.io image fails

### ISSUE THREAD

**Issue by RadekKapica** [microsoft/azure-container-apps#352]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When trying to deploy a container app with a container image i a private docker registry you receive the following error:

The following field(s) are either invalid or missing. Invalid value: "\<registry\>/\<image\>:\<tag\>": GET https:: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:\<registry\>/\<image\> Type:repository]]: template.containers.\<containername\>.image.

### Steps to reproduct
1.  Open Cloud Shell in portal
2.  upload yml-file
 ```
kind: containerapp
location: westeurope
name: \<name>
resourceGroup: \<resourcegroup\>
type: Microsoft.App/containerApps
tags:
  tagname: value
properties:
  managedEnvironmentId: /subscriptions/\<subscriptionId\>/resourceGroups/DefaultResourceGroup-WEU/providers/Microsoft.App/managedEnvironments/\<environmentname\>
  configuration:
    activeRevisionsMode: Multiple
    secrets:
      - name: mysecret
        value: thisismysecret
      - name: myregistrypassword
        value: \<registrypassword\>
    ingress:
      external: true
      allowInsecure: false
      targetPort: 80
      traffic:
        - latestRevision: true
          weight: 100
      transport: Auto
    registries:
      - passwordSecretRef: myregistrypassword
        server: docker.io
        username: \<username\>
  template:
    revisionSuffix: r
    containers:
      - image: \<username\>/\<image\>:\<tag\>
        name: <containername>
        env:
          - name: HTTP_PORT
            value: 80
          - name: secret_name
            secretRef: mysecret
        resources:
          cpu: 0.25
          memory: 0.5Gi
    scale:
      minReplicas: 1
      maxReplicas: 1
 ```
3.  `az containerapp create -n <name> -g <resourcegroup> --environment <environment> --yaml "<yaml-file>"`

**Expected behavior** [What you expected to happen.]
Successfully deployed container app

**Actual behavior** [What actually happened.]
Deployment fails

**Screenshots**         
![image](https://user-images.githubusercontent.com/49438343/183747794-e7c4b178-d04b-4930-bbb6-4dee0a2c011d.png)

### Additional context
Ex. Did this issue occur in the CLI or the Portal?

Same issue occurs in both CLI and Portal

**Comment by CamiloTerevinto** [comment]
Same problem happening here. Adding more information:

- The Portal doesn't save the Registry (possibly since deployment fails?). Manually creating the registry using `az containerapp registry set` does not help.
- Using `az containerapp up` and passing in registry server/username/password fails with the exact same error. 

Using `--debug` flag, this is what fails:

```
urllib3.connectionpool: https://management.azure.com:443 "PATCH /subscriptions/**omitted**/resourceGroups/**omitted**/providers/Microsoft.App/containerApps/**omitted**?api-version=2022-03-01 HTTP/1.1" 400 350
cli.azure.cli.core.util: Response status: 400
cli.azure.cli.core.util: Response headers:
cli.azure.cli.core.util:     'Cache-Control': 'no-cache'
cli.azure.cli.core.util:     'Pragma': 'no-cache'
cli.azure.cli.core.util:     'Content-Length': '350'
cli.azure.cli.core.util:     'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.util:     'Expires': '-1'
cli.azure.cli.core.util:     'x-ms-ratelimit-remaining-subscription-resource-requests': '499'
cli.azure.cli.core.util:     'api-supported-versions': '2022-01-01-preview, 2022-03-01, 2022-05-01, 2022-06-01-preview'
cli.azure.cli.core.util:     'Server': 'Microsoft-IIS/10.0'
cli.azure.cli.core.util:     'X-Powered-By': 'ASP.NET'
cli.azure.cli.core.util:     'x-ms-request-id': 'f041a2a8-4058-49b0-a469-8edaeb125e1e'
cli.azure.cli.core.util:     'x-ms-correlation-request-id': 'f041a2a8-4058-49b0-a469-8edaeb125e1e'
cli.azure.cli.core.util:     'x-ms-routing-request-id': 'UKSOUTH:20220810T085332Z:f041a2a8-4058-49b0-a469-8edaeb125e1e'
cli.azure.cli.core.util:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.util:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.util:     'Date': 'Wed, 10 Aug 2022 08:53:31 GMT'
cli.azure.cli.core.util: Response content:
cli.azure.cli.core.util: {"code":"WebhookInvalidParameterValue","message":"The following field(s) are either invalid or missing. Invalid value: \"docker.io/**omitted**/**omitted**:159\": GET https:: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:**omitted**/**omitted** Type:repository]]: template.containers.**omitted**.image."}
```

**Comment by vturecek** [comment]
The image string should be `<server>/<image>:<tag>`, not `<username>/<image>:<tag>`. For example:

```
..
registries:
     - passwordSecretRef: myregistrypassword
       server: docker.io
       username: myuser
 template:
   revisionSuffix: r
   containers:
     - image: docker.io/myimage:tag
..
```

We match the server part of the value in the `image` field to the `server` field in one of the entries in `registries`. If we don't find a match, then we try an anonymous pull, which fails with unauthorized as you see here.
