### ISSUE TITLE
Feature Request: Mount Secrets as Volume

### ISSUE THREAD

**Issue by lastcoolnameleft** [microsoft/azure-container-apps#360]
**Is your feature request related to a problem? Please describe**.  
I would like to mount secrets in ACA as a file.  Essentially, I would like to enable this feature in K8S:
https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod

**Describe the solution you'd like**.    
I'm not picky about the implementation, but an example solution would be:
```
properties:
    configuration:
        secrets:
        - name: myymountedsecret
          value: <BASE64 encoded value of file>
...
    template:
        containers:
        - name: foo
          volumeMounts:
          - volumeName: secrets
            secretRef: myymountedsecret
            mountPath: /mnt/secrets/
```

**Describe alternatives you've considered**.   
Currently, to mount a secret, I can either:
  * Bake the secret into the image.  BAD!
  * Use an [SMB Storage Mount](https://docs.microsoft.com/en-us/azure/container-apps/storage-mounts?pivots=aca-cli#azure-files).  Works, but not as secure.

**Additional context**.  
Given this is working functionality in K8S, it would be nice to be able to use it here too.
