### ISSUE TITLE
Dapr + Redis - connection pool timeout

### ISSUE THREAD

**Issue by k-schneider** [microsoft/azure-container-apps#365]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [X] regression (a behavior that used to work and stopped in a new release)

### Issue description
I've had a hobby project deployed via container apps since May that ran with zero issues until very recently (the last week or so). I'm leveraging Dapr for pubsub and state backed by Redis and the daprd container log stream is spitting this out on repeat:

```
2022-08-18T03:34:15.520779106Z time="2022-08-18T03:34:15.520525903Z" level=error msg="redis streams: error reading from stream Redacted: redis: connection pool timeout" app_id=redacted instance=redacted scope=dapr.contrib type=log ver=1.8.3-msft-1
2022-08-18T03:34:16.205565661Z time="2022-08-18T03:34:16.205382359Z" level=error msg="error retrieving pending Redis messages: redis: connection pool timeout" app_id=redacted instance=redacted scope=dapr.contrib type=log ver=1.8.3-msft-1
```

I've tried pointing it at different Redis instances to try and narrow down the issue but nothing seems to make a difference.  The app still works on my local machine with the latest versions of Dapr + Redis.

Any help troubleshooting this would be greatly appreciated.  Thanks.

**Comment by k-schneider** [comment]
I set poolSize to 20 and it seems to be working now but I'm going to leave this up for now since it was previously working and this just recently became an issue.

**Comment by ItalyPaleAle** [comment]
Hi @k-schneider Can you please provide a few more details:

1. Where is your Redis server hosted? Are you using a managed service or self-hosting it somewhere?
2. What version of Redis are you using?
3. How do you connect to it?
4. What kind of jobs are you performing after receiving them from Redis? How long does each handler take, on average?
5. What's the value of the `concurrency` metadata option?
6. Any other information that you can share that you feel would be relevant?

**Comment by k-schneider** [comment]
Sure I'll do my best:

> 1. Where is your Redis server hosted? Are you using a managed service or self-hosting it somewhere?
Its an additional container within the same container app (scale is set to 1).

> 2. What version of Redis are you using?
`docker.io/redis:alpine`

> 3. How do you connect to it?
I'm using Dapr so I'm not connecting to it directly.  I'm leveraging it for both pubsub as well as state store for actors. Here's a snippet from my bicep:

```yaml
resource statestoreComponent 'daprComponents' = {
  name: 'statestore'
  properties: {
    componentType: 'state.redis'
    version: 'v1'
    ignoreErrors: false
    initTimeout: '1m'
    secrets: [
      {
        name: 'redis-password'
        value: 'password'
      }
    ]
    metadata: [
      {
        name: 'redisHost'
        value: '127.0.0.1:6379'
      }
      {
        name: 'redisPassword'
        secretRef: 'redis-password'
      }
      {
        name: 'actorStateStore'
        value: 'true'
      }
      {
        name: 'poolSize'
        value: '20'
      }
    ]
    scopes: [
      containerAppName
    ]
  }
}
resource pubsubComponent 'daprComponents' = {
  name: 'pubsub'
  properties: {
    componentType: 'pubsub.redis'
    version: 'v1'
    ignoreErrors: false
    initTimeout: '1m'
    secrets: [
      {
        name: 'redis-password'
        value: 'password'
      }
    ]
    metadata: [
      {
        name: 'redisHost'
        value: '127.0.0.1:6379'
      }
      {
        name: 'redisPassword'
        secretRef: 'redis-password'
      }
      {
        name: 'poolSize'
        value: '20'
      }
    ]
    scopes: [
      containerAppName
    ]
  }
}
```

> 4. What kind of jobs are you performing after receiving them from Redis? How long does each handler take, on average?
When it's working everything is near instant since its all running over localhost.

> 5. What's the value of the `concurrency` metadata option?
I don't currently have this set.  Docs for pubsub.redis seem to indicate the default is 10.

> 6. Any other information that you can share that you feel would be relevant?
Like I said above, bumping the poolSize to 20 fixed it but I'm not sure why.
