### ISSUE TITLE
Consider allowing longer Azure Container Registry names

### ISSUE THREAD

**Issue by mikeball** [microsoft/azure-container-apps#41]
```
az containerapp update -n hellocustomuser -g mygroupname \
    --image toolongregistryname.azurecr.io/hello-world:4cb5f89 \
    --secrets mypassword=verysecurepassword \
    --registry-login-server toolongregistryname.azurecr.io \
    --registry-username MYGUIDab-4a32-11ec-ba16-00155dbf35bc \
    --registry-password **********************************

Invalid value: "toolongregistrynameazurecrio-MYGUIDab-4a32-11ec-ba16-00155dbf35bc": Length must be no more than 63 characters: configuration.secrets.
```

So using Azure Container Registry along with a service principal login (which unfortunately uses a guid as username) the naming scheme takes up 46 characters by default, leaving only 16 characters max for the registry name, which in my test case was exceeded by a few characters.

**Comment by mikeball** [comment]
related to issue. https://github.com/microsoft/azure-container-apps/issues/10

**Comment by mikeball** [comment]
Using the yaml file work around mentioned in https://github.com/microsoft/azure-container-apps/issues/10#issuecomment-967430684 was able to use a secret name that is shorter.

```
> az containerapp update --resource-group myresourcegroup --name myappname --yaml app.yaml
```
app.yaml
```yaml
kubeEnvironmentId: "/subscriptions/..."
configuration:
  ingress:
    external: true
    targetPort: 8080
  activeRevisionsMode: single
  registries:
  - server: myregistry.azurecr.io
    username: myguid
    passwordSecretRef: registry-password
  secrets:
  - name: registry-password
    value: "mysecret"
template:
  containers:
  - image: myregistry.azurecr.io/hello-world:4cb5f89
    name: hello-world
    resources:
      cpu: 0.25
      memory: .5Gi
  scale:
    maxReplicas: 3
    minReplicas: 0

```
