### ISSUE TITLE
Feature Request: Container Apps DAPR config parameter

### ISSUE THREAD

**Issue by lurock** [microsoft/azure-container-apps#412]
Does container apps support passing in a config parameter so I can scope secrets?  How would I do this in Container Apps?

Locally you can run your app and pass the config in.  Then your app can only access the secrets you define:

dapr run --app-id myApp --config config.yaml

config.yaml
``` 
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  secrets:
    scopes:
      - storeName: vault
        defaultAccess: deny
        allowedSecrets: ["secret1", "secret2"]
```

Here are the docs from DAPR on this:

https://docs.dapr.io/developing-applications/building-blocks/secrets/secrets-scopes/#scenario-1--deny-access-to-all-secrets-for-a-secret-store
