### ISSUE TITLE
Feature Request: Declarative pub/sub subscriptions

### ISSUE THREAD

**Issue by epomatti** [microsoft/azure-container-apps#413]
**Describe the solution you'd like**.    

Is declarative subscription considered in the roadmap? As stated in the [docs](https://learn.microsoft.com/en-us/azure/container-apps/dapr-overview?tabs=bicep1%2Cyaml#known-limitations):

> **Known limitations**
> - Declarative pub/sub subscriptions

**Describe alternatives you've considered**.   

It is possible to do programmatic subscription only.

**Additional context**.  

There are [two methods of subscribing to pub/sub topics](https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/):
- Declarative - Not Supported 😔
  ```yaml
  apiVersion: dapr.io/v1alpha1
  kind: Subscription
  metadata:
    name: order
  spec:
    topic: orders
    route: /checkout
    pubsubname: pubsub
  scopes:
  - orderprocessing
  - checkout
  ```

- Programmatic - Supported ✅
  ```js
  app.get('/dapr/subscribe', (_req, res) => {
      res.json([
          {
              pubsubname: "orderpubsub",
              topic: "orders",
              route: "orders"
          }
      ]);
  });
  ```
