### ISSUE TITLE
Missing example of a file passed to `--scale-rules` param

### ISSUE THREAD

**Issue by L-Sypniewski** [microsoft/azure-container-apps#42]
Hi,
May anyone provide an example of a file with scale rules used for example in an update command: `az containerapp update --name $CONTAINER_APP_NAME --resource-group $RESOURCE_GROUP --scale-rules scale.yaml`?

I've tried using output from `az containerapp show --output yaml`, but with no success:
```yaml
scale:
      maxReplicas: 5
      minReplicas: 0
      rules:
      - azureQueue: null
        custom: null
        http:
          auth: null
          metadata:
            concurrentRequests: '1'
        name: httpscale
```

Thanks in advance

**Comment by ahmelsayed** [comment]
@L-Sypniewski The file should be just the `rules` array from https://docs.microsoft.com/en-us/azure/container-apps/scale-app 

For example, if you want to configure an http scale rule, you can do 
 
```yaml
- name: httpscale
  http:
    metadata:
      concurrentRequests: '1'
```

and you can use 

```
az containerapp update --name $CONTAINER_APP_NAME \
    --resource-group $RESOURCE_GROUP \
    --min-replicas 0 \
    --max-replicas 5 \
    --scale-rules scale.yaml
```

If you want to add another rule to the same app (so the app will scale if concurrentRequests > 1 OR the average CPU > 75%


```yaml
- name: httpScale
  http:
    metadata:
      concurrentRequests: '1'
- name: cpuScaleRule
  custom:
    type: cpu
    metadata:
      type: AverageValue
      value: '75'
```

**Comment by takekazuomi** [comment]
--dapr-components is also undocumented.

**Comment by L-Sypniewski** [comment]
@takekazuomi An example can be found [here](https://docs.microsoft.com/en-us/azure/container-apps/microservices-dapr?tabs=bash#configure-the-state-store-component). According to the docs:

> Container Apps does not currently support the native Dapr components schema. The above example uses the supported schema.

**Comment by L-Sypniewski** [comment]
@ahmelsayed I've tried using file format you suggested, but I'm getting the following error: `--scale-rules: type field required in rules config`. 
Command I used: `az containerapp update --name $CONTAINER_APP_NAME --resource-group $RESOURCE_GROUP --scale-rules scale.yaml`

I managed to run the command using the following file:
```yaml
- name: cpuscalerule
  custom:
  type: cpu
  metadata:
    type: AverageValue
    value: '75'
- name: httpscalerule
  type: http
  metadata:
    concurrentRequests: '4'
```
Unfortunately CPU rule is not applied as the output after running the command is as follows:
```json
"rules": [
        {
          "azureQueue": null,
          "custom": null,
          "http": {
            "auth": null,
            "metadata": {
              "concurrentRequests": "4"
            }
          },
          "name": "httpscaleyaml"
        }
      ]
```

**Comment by ahmelsayed** [comment]
/cc @calvinsID 

@L-Sypniewski it should be 

```diff
 - name: cpuscalerule
   custom:
-  type: cpu
-  metadata:
-    type: AverageValue
-    value: '75'
+    type: cpu
+    metadata
+      type: AverageValue
+      value: '75'
 - name: httpscalerule
   type: http
   metadata:
     concurrentRequests: '4'
```
note the extra indentations. or you can use JSON too

```json
[
  {
    "name": "cpuScaleRule",
    "custom": {
      "type": "cpu",
      "metadata": {
        "type": "AverageValue",
        "value": "75"
      }
    }
  },
  {
    "name": "httpScale",
    "http": {
      "metadata": {
        "concurrentRequests": "1"
      }
    }
  }
]
```

```
az containerapp update --name $CONTAINER_APP_NAME --resource-group $RESOURCE_GROUP --scale-rules scale.json
```

**Comment by L-Sypniewski** [comment]
@ahmelsayed thanks for your reply.

As for CPU rules neither .yaml with fixed indentations nor .json work for me - I'm still getting `--scale-rules: type field required in rules config` error. Regarding http scaling I had to modify the .json file as follows:
```json
[
  {
    "name": "httpscale",
    "type": "http",
    "metadata": {
      "concurrentRequests": "8"
    }
  }
]
```

**Comment by calvinsID** [comment]
Hey @L-Sypniewski can you please try doing the update using the `--yaml` parameter? Unfortunately the `--scale-rules` flag is buggy, it will also be deprecated & removed soon in favor of the `--yaml` parameter

**Comment by frbar** [comment]
Hi - same issue as @L-Sypniewski .

`type field required in rules config` with a Json file and `--scale-rules`.

Trying with the YAML equivalent, and `--scale-rules` or `--yaml`:

```
- name: queue-based-autoscaling
  custom:
    type: azure-servicebus
    metadata:
      queueName: jobs
      messageCount: '5'
    auth:
    - secretRef: servicebusconnectionstring
      triggerParameter: connection
```
--> `AttributeError: 'list' object has no attribute 'get'`

**Comment by frbar** [comment]
With `--scale-rules` and this content, there is no error, but the scale rule is not created (the revision is).

```
- name: queue-based-autoscaling
  type: azure-servicebus                  # add this line
  custom:
    type: azure-servicebus                # remove this line
    metadata:
      queueName: jobs
      messageCount: '5'
    auth:
    - secretRef: servicebusconnectionstring
      triggerParameter: connection
```

Command is: 
```
az containerapp create `
  --name XXX `
  --resource-group XXX `
  --environment XXX `
  --image XXX `
  --secrets "servicebusconnectionstring=$xxx,blobstorageconnectionstring=$xxx" `
  --environment-variables "xxx" `
  --registry-login-server XXX `
  --registry-username XXX `
  --registry-password XXX `
  --min-replicas 1 `
  --max-replicas 1 `
  --scale-rules scale-rules.yaml
  ```

Same without `--min-replicas` and `--max-replicas`.
