### ISSUE TITLE
Access environment variables in yaml

### ISSUE THREAD

**Issue by mikeball** [microsoft/azure-container-apps#43]
The ability to access environment variables from within the yaml files when used from azure cli would be EXTREMELY helpful. 

We are unable/unwilling to store sensitive data in yaml files which get checked into source control, and so only make them available as environment variables. For example the `<PasswordGoesHere>` placeholder in the yaml file below, but also many other items such as `<subscription>, <rg>, <image>, etc..`

```
> az containerapp update --resource-group myresourcegroup --name myappname --yaml app.yaml
```
app.yaml:
```yaml
kubeEnvironmentId: /subscriptions/<subscription>/resourceGroups/<rg>/providers/Microsoft.Web/kubeEnvironments/<environment name>
configuration:
  activeRevisionsMode: multiple
  registries:
  - server: myacr.azurecr.io
    username: someuser
    passwordSecretRef: acr-password
  secrets:
  - name: acr-password
    value: <PasswordGoesHere>
template:
  containers:
  - image: myacr.azurecr.io/myimage:tag
    name: myimage
    resources:
      cpu: 0.5
      memory: 1Gi
  scale:
    maxReplicas: 1
    minReplicas: 0
```

Perhaps the yaml file would allow placeholders `${SUBSCRIPTION}` and `${REGISTRY_PASSWORD}` which could be replaced by  environment variables `SUBSCRIPTION` and `REGISTRY_PASSWORD`.

```yaml
kubeEnvironmentId: /subscriptions/${SUBSCRIPTION}/resourceGroups/<rg>/providers/Microsoft.Web/kubeEnvironments/<environment name>
configuration:
  activeRevisionsMode: multiple
  registries:
  - server: myacr.azurecr.io
    username: someuser
    passwordSecretRef: acr-password
  secrets:
  - name: acr-password
    value: ${REGISTRY_PASSWORD}
template:
  containers:
  - image: myacr.azurecr.io/myimage:tag
    name: myimage
    resources:
      cpu: 0.5
      memory: 1Gi
  scale:
    maxReplicas: 1
    minReplicas: 0
```

**Comment by gpltaylor** [comment]
personally I don't see this being a feature or engine of Azure Container Apps. I think development teams should choose their own implementation.

For example, as this is Kubernetes "under the hood" a great choice would be Helm. But if this is a little heavy for the development team, you can also choose mustache.

**Resources** 
Working with Helm Secrets
https://www.youtube.com/watch?v=hRSlKRvYe1A

https://github.com/jkroepke/helm-secrets

Mustache YAML variables 
https://mustache.github.io/mustache.1.html

**Comment by SatyKrish** [comment]
Azure App Configuration be considered here to manage config and secrets required for container apps.

**Comment by mikeball** [comment]
Practical option for now, just made a small script to use a template yaml file and generate a yaml file with the secrets in it, which is then deleted immediately after using as `--yaml` parameter.

container-app.tpl.yaml
```yaml
kubeEnvironmentId: /subscriptions/${AZ_SUBSCRIPTION}/resourceGroups/${AZ_RESOURCEGROUP}/providers/Microsoft.Web/kubeEnvironments/${AZ_APPENVIRONMENT}
configuration:
  ingress:
    external: true
    targetPort: 8080
  activeRevisionsMode: single
  registries:
  - server: ${REGISTRY_SERVER}
    username: ${REGISTRY_USERNAME}
    passwordSecretRef: registry-password
  secrets:
  - name: registry-password
    value: ${REGISTRY_PASSWORD}
template:
  containers:
  - image: ${CONTAINER_IMAGE}
    name: echo-gateway
    resources:
      cpu: 0.25
      memory: .5Gi
  scale:
    maxReplicas: 5
    minReplicas: 0
```

generate-container-app-yaml-file.sh :
```bash
# remove generated files
rm -rf out/*

# create script file that will pick up environment vars
# and replace placeholders in the yaml template
( echo "cat <<EOF >out/container-app.yaml";
  cat container-app.tpl.yaml;
  # echo "EOF";
) >out/create-container-app.yaml.sh

# create the yaml file with env vars
./out/create-container-app.yaml.sh

# remove temp script that we used to generate yaml
rm -r out/create-container-app.yaml.sh
```
