### ISSUE TITLE
az containerapp create requires activeRevisionsMode in yaml option

### ISSUE THREAD

**Issue by jeffhollan** [microsoft/azure-container-apps#44]
When using the `--yaml` flag, the yaml fails unless it explicitly defines an activeRevisionsMode. I figured this would be an optional parameter and default to the default (`multiple`).

```yaml
# az containerapp create -n my-store -g my-rg --yaml deploy.yaml
type: Microsoft.Web/containerApps
template:
  containers:
  - name: mystore
    image: ghcr.io/jeffhollan/container-app-aspnet:v0.2
kubeEnvironmentId: /subscriptions/xxxxx-xxxx-xxxx/resourceGroups/mechanics-aca/providers/Microsoft.Web/kubeEnvironments/mechanics-aca
configuration:
  ingress:
    external: true
    targetPort: 80
```

Fails with the following:

> The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 712, in _run_job        
  File "C:\Users\jehollan\.azure\cliextensions\containerapp\azext_workerapp\_client_factory.py", line 38, in _polish_bad_errors
    raise ex
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job        
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__        
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\jehollan\.azure\cliextensions\containerapp\azext_workerapp\custom.py", line 423, in update_containerapp
    return create_or_update_containerapp_yaml(cmd=cmd, client=client, name=name, resource_group_name=resource_group_name, file_name=yaml, is_update=True, no_wait=no_wait)
  File "C:\Users\jehollan\.azure\cliextensions\containerapp\azext_workerapp\custom.py", line 168, in create_or_update_containerapp_yaml   
    if containerapp_def.configuration.active_revisions_mode.lower() == "single":
AttributeError: 'NoneType' object has no attribute 'lower'

```yaml
# az containerapp create -n my-store -g my-rg --yaml deploy.yaml
type: Microsoft.Web/containerApps
template:
  containers:
  - name: mystore
    image: ghcr.io/jeffhollan/container-app-aspnet:v0.2
kubeEnvironmentId: /subscriptions/xxxxx-xxxx-xxxx/resourceGroups/mechanics-aca/providers/Microsoft.Web/kubeEnvironments/mechanics-aca
configuration:
  activeRevisionsMode: multiple
  ingress:
    external: true
    targetPort: 80
```
Succeeds
