### ISSUE TITLE
Creating cron scaling rule with CLI gives internal server error

### ISSUE THREAD

**Issue by jscheeres** [microsoft/azure-container-apps#463]
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Creating a cron scaling rule gives an internal server error from the CLI with version 0.3.13. Creating the cron rule via the azure portal works ok.

### Steps to reproduce

Execute the following CLI command:

_az containerapp update -n \<containerapp-name\> -g \<resource-group\> --yaml scalerule.yaml_

scalerule.yaml file:
```
properties:
  template:
    scale:
      minReplicas: 0
      maxReplicas: 25
      rules:
      - custom:
          auth:
          - secretRef: servicebus
            triggerParameter: connection
          metadata:
            messageCount: '5'
            topicName: $$ENV$$-item-rgg-sbt
            subscriptionName: catalogservice-sub
          type: azure-servicebus
        name: catalogservice-items
      - custom:
          auth:
          - secretRef: servicebus
            triggerParameter: connection
          metadata:
            messageCount: '5'
            topicName: $$ENV$$-rgg-publicationhierarchy-sbt
            subscriptionName: catalogservice-sub
          type: azure-servicebus
        name: catalogservice-publication
      - custom:
          auth:
          - secretRef: servicebus
            triggerParameter: connection
          metadata:
            messageCount: '5'
            queueName: $$ENV$$-rebuildindex-sbq
          type: azure-servicebus
        name: catalogservice-rebuildindex
      - custom:
          auth:
          - secretRef: servicebus
            triggerParameter: connection
          metadata:
            messageCount: '5'
            queueName: $$ENV$$-rebuildfullindex-sbq
          type: azure-servicebus
        name: catalogservice-rebuildfullindex
      - custom:
          medadata:
            timezone: Europe/Amsterdam
            start: 55 23 * * *
            end: 35 0 * * *
            desiredReplicas: '1'
          type: cron
        name: timer-jobs
```

**Expected behavior** 

The scaling rule with type cron and name times-jobs should be created.

**Actual behavior**

Internal server error occurred. correlation ID: c7d72a8f-8956-46af-9ba0-308c8de3f9ca

**Screenshots**         
![image](https://user-images.githubusercontent.com/10026982/197138750-2d8ddfdc-6324-4207-81a5-3ba22deddf80.png)
