### ISSUE TITLE
az containerapp update --yaml does not remove scale rule if it was not written in yaml

### ISSUE THREAD

**Issue by georgeOsdDev** [microsoft/azure-container-apps#516]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

`az containerapp update --yaml` does not remove scale rules.
If no scale rule is specified, it will not be empty, but will inherit the existing revision's scale rule.

### Steps to reproduce
1. Create revision with some scale rule
`az containerapp update --name <name> --resource-group <rg> --yaml withrule.yaml`
```
properties:
  configuration:
    activeRevisionsMode: single
  template:
    revisionSuffix: '01'
    containers:
    - image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
      name: c1
      probes: []
      resources:
        cpu: 0.25
        ephemeralStorage: ''
        memory: 0.5Gi
    scale:
      maxReplicas: 10
      minReplicas: 1
      rules:
      - http:
          metadata:
            concurrentRequests: 200
          type: http
        name: http-rule
```

2. Update revision without scale rule
`az containerapp update --name <name> --resource-group <rg> --yaml norule.yaml`
```
properties:
  configuration:
    activeRevisionsMode: single
  template:
    revisionSuffix: '02'
    containers:
    - image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
      name: c1
      probes: []
      resources:
        cpu: 0.25
        ephemeralStorage: ''
        memory: 0.5Gi
    scale:
      maxReplicas: 10
      minReplicas: 1
```

**Expected behavior** [What you expected to happen.]

Newly created revision should not have scale rule.
Because scale rule is revision scope.
https://learn.microsoft.com/en-us/azure/container-apps/revisions#revision-scope-changes

**Actual behavior** [What actually happened.]

Newly created revision inherit scale rule from previous one
```
    "provisioningState": "Succeeded",
    "template": {
      "containers": [
        {
          "image": "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest",
          "name": "c1",
          "resources": {
            "cpu": 0.25,
            "ephemeralStorage": "",
            "memory": "0.5Gi"
          }
        }
      ],
      "revisionSuffix": "02",
      "scale": {
        "maxReplicas": 10,
        "minReplicas": 1,
        "rules": [
          {
            "http": {
              "metadata": {
                "concurrentRequests": "200"
              }
            },
            "name": "http-rule"
          }
        ]
      }
    }
  },
```

**Screenshots**         

### Additional context
I use az cli with below environment
```
$ az --version
azure-cli                         2.42.0

core                              2.42.0
telemetry                          1.0.8

Extensions:
appservice-kube                    0.1.7
connectedk8s                       1.3.5
containerapp                      0.3.16
customlocation                     0.1.3
k8s-extension                      1.3.6

Dependencies:
msal                              1.20.0
azure-mgmt-resource             21.1.0b1
```
