### ISSUE TITLE
Edit Environment variables in Portal

### ISSUE THREAD

**Issue by jucabot** [microsoft/azure-container-apps#52]
How to edit the environnement variables into Azure Portal?

**Comment by mikeball** [comment]
Is there any way at all to set environment variables right now?

**Comment by mikeball** [comment]
To help others looking to set environment vars, I found 2 ways to do this.

1. Use the update command
```
> az containerapp update --resource-group myapp-rg --name myapp --environment-variables EXAMPLE_VAR1=abc,EXAMPLE_VAR2=123
```

2. Use a yaml file with update command (only relevant section of yaml shown)
```
template:
  containers:
  - image: mycontainerimage
    name: myapp
    env:
    - name: EXAMPLE_VAR1
      value: abc
    - name: EXAMPLE_VAR2
      value: 123
```
