### ISSUE TITLE
Feature Request: Dapr resiliency policies

### ISSUE THREAD

**Issue by joeklin** [microsoft/azure-container-apps#548]
**Is your feature request related to a problem? Please describe**.  
 Retry and circuit breaker patterns for failed events with deadlettering in place requires custom code

**Describe the solution you'd like**.    
We would like to be able to set declarative resiliency policies for dapr components. 
Similar to https://docs.dapr.io/operations/resiliency/policies/ 

**Describe alternatives you've considered**.   
Custom code to manage the policies

**Additional context**.  
We recently switched from Azure Service Bus to Azure Event Hubs to take advantage of the event capture native to event hubs. Doing this, we lost dead lettering and the ability to configure retries. Dead lettering was solved by upgrading to the latest version of dapr and updating our code. But the messages will go to the dead letter queue with no retries.

**Comment by calleo** [comment]
Apparently this is "in development": https://github.com/microsoft/azure-container-apps/issues/585

**Comment by greenie-msft** [comment]
@joeklin, 

The resiliency feature is now available in ACA: https://techcommunity.microsoft.com/t5/azure-developer-community-blog/resiliency-policies-now-available-in-azure-container-apps/ba-p/3978864

Supporting circuit breakers for Dapr components will be available in the very near future. Please let me know if you have any questions or feedback as you try out resiliency policies in ACA.

**Comment by greenie-msft** [comment]
@joeklin,

One follow up question - What are you using for a trip expression for your component circuit breakers? consecutiveErrors?

**Comment by joeklin** [comment]
It has been a while but I think that's what we had in place. If I remember correctly DAPR documentation doesn't lay out what is CELs would be recognized and since it wasn't in ACA yet, we didn't really dive in very deeply.

**Comment by christophwille** [comment]
@greenie-msft are there plans to expand the available dapr resiliency policies? Very specifically I am looking for the retry policies on pubsub:

``` yml
# https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-deadletter/#retries-and-dead-letter-topics
# https://docs.dapr.io/operations/resiliency/policies/#retries

apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: samplepolicy
spec:
  policies:
    retries:
      pubsubRetry:
        # production: exponential
        policy: constant
        duration: 5s
        maxRetries: 10
  targets:
    components:
      mypubsub:
        inbound:
          retry: pubsubRetry
```

Thanks.
