### ISSUE TITLE
`container app create` CLI: a necessary `command` option is missing from YAML file but available as CLI and Azure Portal parameter

### ISSUE THREAD

**Issue by askaribragimov** [microsoft/azure-container-apps#570]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report 

### Issue description
According to https://learn.microsoft.com/en-us/cli/azure/containerapp?view=azure-cli-latest#az-containerapp-create, 
container app can be created using a YAML template that actually looks much nicer than issuing lots of command line parameters.

However, CLI parameter `--command` that is vital to some containers to run the service (for instance, if the container has to run some server process), which is also configurable via Azure Portal, has **no option in YAML according to documentation** and how to configure this parameter via YAML file remains unknown. Adding `--command` together with `--yaml` option also does not make the command to be specified. 
 
**Expected behavior** [What you expected to happen.]

YAML in question should have documented `command` parameter/entry that mirrors CLI `--command` parameter necessary to run container properly.

**Actual behavior** [What actually happened.]

Missing completely 

**Screenshots**         

### Additional context
CLI and YAML parameter file
Extension 'containerapp' 0.3.20

**Comment by anthonychu** [comment]
To use `command` in YAML, you can supply an array like in the snippet below. The docs are being updated to add it to the YAML reference. Thanks for pointing this out this omission.

```yaml
# ...
  template:
    revisionSuffix: myrevision
    containers:
      - image: nginx
        name: nginx
        env:
          - name: HTTP_PORT
            value: 80
          - name: secret_name
            secretRef: mysecret
        command:
          - npm
          - start
# ...
```
