### ISSUE TITLE
Roadmap: KEDA Scale with Managed Identity

### ISSUE THREAD

**Issue by SophCarp** [microsoft/azure-container-apps#592]
No ETA yet

**Comment by Ralle1986** [comment]
any ETA on this ?

**Comment by preardon** [comment]
Anything we can do to increase the priority on this?

**Comment by andreaskasc** [comment]
We would really need this feature.  Is there any update for it?

**Comment by preardon** [comment]
> We would really need this feature. Is there any update for it?

Agreed, this is a bit of a blocker for us moving to ACA

**Comment by onionhammer** [comment]
Yes please, this would be tremendous

**Comment by KamilLach** [comment]
This will be a great improvement for our ACA architecture

**Comment by Superzer0** [comment]
+1

**Comment by ezYakaEagle442** [comment]
Hi @SophCarp could you please share an ETA ?

**Comment by coin-op** [comment]
Please can this be sorted out @SophCarp. 1 year on a backlog!

**Comment by mjrousos** [comment]
Needing a SAS-based connection string for KEDA scaling is the only reason I need local authentication enabled on a Service Bus namespace for the solution I'm working on. Everything else authenticates with managed identity. It would be great to add support for that here.

**Comment by preardon** [comment]
Needing SAS for KEDA is the reason why we've not moved to ACA or KEDA as yet, I refused to lower security

**Comment by jemrpo** [comment]
I ended up implementing a microservice to get around this restriction, I'd be great if the product team gives this a higher priority. I'd help a lot of people to simplify their applications.

**Comment by preardon** [comment]
> I ended up implementing a microservice to get around this restriction, I'd be great if the product team gives this a higher priority. I'd help a lot of people to simplify their applications.

I'm assuming you implemented a hosted service with a timer that used the managed Identity with the Service Bus Administration client, what did you use for the ACA side, just HTTP or is there a programetic way to tell it to - scale

**Comment by jemrpo** [comment]
@preardon my app is not using service bus. 

KEDA is forcing me to use some info and a token for authentication in order to scale, I did not want to use a regular token because this would be insecure. 
I ended up creating a microservice which uses a User Assignment Identity to request an ephemeral bearer token from Azure, once it gets the token, it stores it on a KV that is linked to the ACA secrets, and monitors the token life to request a new one once it expires. 

I've been using this approach with ACA apps and Jobs, is working fine and I'm able to scale from 0 to 30 in a few seconds.

The life of the bearer token varies but it's never valid for more than 24 hours, it is not perfect, but it's way better than manually rotating tokens every 3 or 6 months.

Please let me know if this answers your question or if you want me to add more details.

**Comment by preardon** [comment]
@jemrpo nice and clear, thank you.

**Comment by vturecek** [comment]
Hi everyone, we are actively working on this and expect it to be available in an upcoming API version. We will provide an ETA soon.

**Comment by oscarmh** [comment]
what is soon ?

**Comment by Dionmm** [comment]
Hi @vturecek any update on a possible ETA at least?

**Comment by alvgarvilla** [comment]
H @vturecek , any update please?

**Comment by ReneRebsdorf** [comment]
This would be very useful, and have been watching for this for about a year now.
The communication leaves something to be desired :-(

**Comment by zyofeng** [comment]
Our Azure Defender for Cloud is picking up SAS usage key for KEDA as potential attack surface, 

I would appreciate the ability to integrate with managed identity (container instance), or workload identity (container app) below:

https://keda.sh/docs/2.13/authentication-providers/azure-ad-workload-identity/

**Comment by DenisBalan** [comment]
Missing feature, eta?

**Comment by fgheysels** [comment]
We're using ACA as well, and are using KEDA scalers on a service bus topic.  Unfortunately, our client / customer who's ISO certified doesn't like it that we need to use a connection-string with shared access key here.

**Comment by verschaevesiebe** [comment]
Any update on this ? We've setup KEDA scaler to service bus but customer doesn't allow SAS keys to be used.
Microsoft pushes towards identity usage & rbac management but this blocks us from using Container Jobs tbh.

Please update ?

**Comment by vturecek** [comment]
Hi everyone, thanks for your patience on this. KEDA support for managed identity is rolling out, docs are getting prepped for publishing, and we will be announcing availability before the end of the month.

**Comment by Hi-Fi** [comment]
Seems that KEDA got updated already at least in Sweden Central region. Should managed identities already work or is there some wrapper in between that requires also changes @vturecek?

**Comment by vturecek** [comment]
@Hi-Fi yes this now available in all regions with API version 2024-02-02-preview.

I am still waiting on editing and publication of additional documentation, but this should get you started: https://learn.microsoft.com/en-us/azure/container-apps/managed-identity?tabs=portal%2Cdotnet#use-managed-identity-for-scale-rules

Thanks for your patience. I'll post links to additional documentation once it is published. Please let us know if you have any feedback.

**Comment by vturecek** [comment]
Additional documentation is now available:
https://learn.microsoft.com/en-us/azure/container-apps/scale-app?pivots=azure-cli#authentication-1

API reference: https://learn.microsoft.com/en-us/rest/api/containerapps/container-apps/create-or-update?view=rest-containerapps-2024-02-02-preview&tabs=HTTP#scalerule

**Comment by preardon** [comment]
@vturecek the links appear to be for azure store account based queues and not azure service bus, is this correct?

**Comment by alexpkent** [comment]
I can confirm this is working however the docs on the above links are targeted at Storage Accounts and incorrect for Service Bus queue scaling for example.

Instead of the [Scale Rule](https://learn.microsoft.com/en-us/rest/api/containerapps/container-apps/create-or-update?view=rest-containerapps-2024-02-02-preview&tabs=HTTP#queuescalerule) requiring a metadata property called 'accountName` as the docs state, it needs a metadata property called `namespace` instead.

**Comment by vturecek** [comment]
Thanks @alexpkent, I'll update that

**Comment by haflidif** [comment]
Are there any examples on how to utilize this with the event driven configuration for azure-pipelines KEDA Scaler in Container App Jobs, or is that still not supporting Managed Identity to monitor the queue in Azure DevOps ? and you still need to use PAT there ?

**Comment by drdr-vincentvm** [comment]
@haflidif I got this working today after a bit of trial and error as I couldn't see how to do it from the docs.

_Don't_ use  `organizationURLFromEnv` in the metadata as you might expect. Keep using the `auth` element to specify the org, just remove the PAT from it.

See this bicep:
```
rules: [
  {
    name: 'azure-pipelines'
    type: 'azure-pipelines'
    metadata: {
      poolName: azureDevopsAgentPool
    }
    auth: [
      {
        secretRef: 'azure-devops-organization-url'
        triggerParameter: 'organizationURL'
      }
    ]
    identity: userManagedIdentity.id
  }
]
```

Set the org URL in your job secrets as well (just as a direct value, no key vault needed) and you're good to go. 

I've now completely eliminated PATs in my self hosted agents on Container App Jobs, it's great.

**Comment by haflidif** [comment]
> @haflidif I got this working today after a bit of trial and error as I couldn't see how to do it from the docs.
> 
> 
> 
> _Don't_ use  `organizationURLFromEnv` in the metadata as you might expect. Keep using the `auth` element to specify the org, just remove the PAT from it.
> 
> 
> 
> See this bicep:
> 
> ```
> 
> rules: [
> 
>   {
> 
>     name: 'azure-pipelines'
> 
>     type: 'azure-pipelines'
> 
>     metadata: {
> 
>       poolName: azureDevopsAgentPool
> 
>     }
> 
>     auth: [
> 
>       {
> 
>         secretRef: 'azure-devops-organization-url'
> 
>         triggerParameter: 'organizationURL'
> 
>       }
> 
>     ]
> 
>     identity: userManagedIdentity.id
> 
>   }
> 
> ]
> 
> ```
> 
> 
> 
> Set the org URL in your job secrets as well (just as a direct value, no key vault needed) and you're good to go. 
> 
> 
> 
> I've now completely eliminated PATs in my self hosted agents on Container App Jobs, it's great.
> 
> 

Awesome 👏 Thank you very much! 

I'll try it out at keep you updated

**Comment by jemrpo** [comment]
> @haflidif I got this working today after a bit of trial and error as I couldn't see how to do it from the docs.
> 
> _Don't_ use `organizationURLFromEnv` in the metadata as you might expect. Keep using the `auth` element to specify the org, just remove the PAT from it.
> 
> See this bicep:
> 
> ```
> rules: [
>   {
>     name: 'azure-pipelines'
>     type: 'azure-pipelines'
>     metadata: {
>       poolName: azureDevopsAgentPool
>     }
>     auth: [
>       {
>         secretRef: 'azure-devops-organization-url'
>         triggerParameter: 'organizationURL'
>       }
>     ]
>     identity: userManagedIdentity.id
>   }
> ]
> ```
> 
> Set the org URL in your job secrets as well (just as a direct value, no key vault needed) and you're good to go.
> 
> I've now completely eliminated PATs in my self hosted agents on Container App Jobs, it's great.

I confirm this works perfectly fine.

**Comment by Dylan-Prins** [comment]
Is this also working for Container jobs? (Microsoft.App/jobs@2024-03-01)

**Comment by Dylan-Prins** [comment]
Can someone tell me what i do wrong:

```yaml
resource managedEnvironment 'Microsoft.App/managedEnvironments@2024-03-01' existing = {
  name: managedEnvironmentName
}

resource userAssignedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-07-31-preview' existing = {
  name: userAssignedIdentityName
}

resource job 'Microsoft.App/jobs@2024-02-02-preview' = {
  name: jobName
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${userAssignedIdentity.id}': {}
    }
  }
  properties: {
    environmentId: managedEnvironment.id
    workloadProfileName: 'Consumption'
    configuration: {
      triggerType: 'Event'
      replicaTimeout: 1800
      replicaRetryLimit: 1
      eventTriggerConfig: {
        replicaCompletionCount: 1
        scale: {
          minExecutions: 0
          maxExecutions: 10
          pollingInterval: 10
          rules: [
            {
              name: 'azure-pipelines'
              type: 'azure-pipelines'
              auth: [
                {
                  triggerParameter: 'organizationURL'
                  secretRef: 'azdo-organization-url'
                }
              ]
              metadata: {
                poolName: poolName
                targetPipelinesQueueLength: '1'
              }
              identity: userAssignedIdentity.id
            }
          ]
        }
      }
      secrets: [
        {
          name: 'azdo-organization-url'
          value: organizationUrl
        }
      ]
    }
  }
}

```
