### ISSUE TITLE
Configmap Support

### ISSUE THREAD

**Issue by SophCarp** [microsoft/azure-container-apps#596]

**Comment by ezYakaEagle442** [comment]
I have a Use Case : Spring Boot App deployed using a ConfigMap instead of the Spring-Config-Server
[https://github.com/ezYakaEagle442/aks-spring-with-config-map](https://github.com/ezYakaEagle442/aks-spring-with-config-map) we need ACA to support ConfigMap to ensure a seamless portability between ACA & AKS.

**Comment by shawndjw** [comment]
I also have a use case for configMaps for a Drupal implementation that my organization is trying to deliver.

**Comment by tiwood** [comment]
Hi @SophCarp, 

I just wanted to know if a public/private preview is available to try this before the actual release?
We have a service that could be deployed with ACA instead of AKS, but we would like to have configmap support for easier migration.

**Comment by mdrakiburrahman** [comment]
Hi @torosent, @SophCarp -

Hope you're well. One of the major blockers we have is our existing Source Code depends heavily on config files being available in privileged directory. In Kubernetes, this was fine, because Kubelet auto-mounts files before Pods start.

Couple questions:
1. Will the `configMap` support work similar to Kubernetes; 

e.g.:

```yaml
    spec:
      containers:
       ....
          volumeMounts:
            - name: kafka-properties-vol
              mountPath: /kafka.properties
              subPath: kafka.properties # <---- Can we mount a specific file to subPath?
      volumes:
        - configMap:
            name: otel-agent-conf
          name: kafka-properties-vol
```

2. Is this still on track for End-of-June?
