### ISSUE TITLE
[dapr] Event Hubs input binding crashes dapr container

### ISSUE THREAD

**Issue by snobu** [microsoft/azure-container-apps#603]
I'm trying to define a dapr Event Hub input binding for my Container App.

Here's what i came up with -

```yaml
componentType: bindings.azure.eventhubs
version: v1
metadata:
  - name: connectionString.    # My Event Hub connection string
    value: Endpoint=sb://iothub-ns-poorlyfund-2415[.....]=;EntityPath=poorlyfundedskynet
  - name: storageAccountName    # Azure Storage Account Name
    value: "SomeStorageAccountNameHere"
  - name: storageAccountKey     # Azure Storage Account Key
    value: "nrkA[....]t2ahsCg=="
  - name: storageContainerName  # Azure Storage Container Name
    value: "SomeContainerNameHere"
scopes:
  - dapr-eventhub # the name of my Container App
```

Initially, i did not have storageAccountName and Key in, and that made the sidecar container fail to start with `storageAccountName is required`, so i got the hint.

Now, the dapr sidecar container just crashes on startup and the system logs don't give me anything useful.

Is there an obvious mistake i'm making in the YAML definition?

This is what i use to apply it -

```
az containerapp env dapr-component set    \
               --name env-dapr-eventhub  \
               --resource-group dapr-eventhub  \
               --dapr-component-name eventhub-input-binding  \
               --yaml components/eventhubs_binding.yaml
```
