### ISSUE TITLE
Error when trying to create a component which contains reference to a secretStoreComponent via CLI

### ISSUE THREAD

**Issue by tjoudeh** [microsoft/azure-container-apps#643]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
When trying to create a component using AZ CLI `az containerapp env dapr-component set` and the component file contains a reference to `secretStoreComponent`. The component is not created on ACA environment and the AZ CLI command returns an error similar to the below:
`(DaprComponentMetadataSecretRefNotFound) SecretRef 'sendgrid-api-key' defined for dapr metadata setting 'apiKey' not found`

### Steps to reproduce
1. Create AKV named `tasks-tracker-akv` and create a secret named "sendgrid-api-key"
2. Use your container app system-identity (ACA Principal ID) and associate it with a `Key Vault Secrets User` AKV role.
3. Create a component file of type `secretstores.azure.keyvault` using the yaml file below and use AZ CLI to create Dapr Secret Store on ACA environment:
```yaml
componentType: secretstores.azure.keyvault
version: v1
metadata:
  - name: vaultName
    value: tasks-tracker-akv
scopes:
  - tasksmanager-backend-processor
```
4. Create a component file that contains a reference to secretStoreComponent and a secret key stored in AKV similar to the below: 
```yaml
componentType: bindings.twilio.sendgrid
version: v1
secretStoreComponent: "secretstoreakv"
metadata:
- name: emailFrom
  value: "email@gmail.com"
- name: emailFromName
  value: "Email Subject"
- name: apiKey
  secretRef: sendgrid-api-key
scopes:
- tasksmanager-backend-processor
```
5. Try to create the Dapr componenet on ACA environment using AZ CLI similar to the command below:
```powershell
az containerapp env dapr-component set ` 
--name $ENVIRONMENT 
--resource-group $RESOURCE_GROUP `
--dapr-component-name sendgrid `
--yaml '.\aca-components\sendgrid.yaml'
```
6. Command `az containerapp env dapr-component set` will fail similar to the error below
<img width="900" alt="image" src="https://user-images.githubusercontent.com/3114431/221254437-750285c9-e781-42b8-818c-d9efbde61800.png">

**Expected behavior** [What you expected to happen.]
The component should be created in ACA environment with the correct settings and `secretRef` metadata key should not cause an issue when using AZ CLI.
Taking into consideration that creating the component works from the Azure Portal UI with no issues.
<img width="301" alt="image" src="https://user-images.githubusercontent.com/3114431/221254766-dc2d7039-0051-40d0-9e72-4df4910fbc60.png">

**Actual behavior** [What actually happened.]
Please check step 6 from the repro

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
CLI, working fine on the Portal. CLI version is up to date.
<img width="883" alt="image" src="https://user-images.githubusercontent.com/3114431/221255896-721eab42-02d2-4191-8382-286739b38edf.png">
