### ISSUE TITLE
az containerapp create --yaml does not support UserAssignedIdentities

### ISSUE THREAD

**Issue by andrewweston** [microsoft/azure-container-apps#662]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

When using Container Apps YAML configuration with a user assigned identity, `az containerapp create --yaml` fails with the exception:

```
ERROR: (InvalidIdentityValues) Invalid value for the identities '/subscriptions/***/resourceGroups/***/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-platform'. The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property.
```

When I use `az containerapp update` with the same YAML file, the update succeeds.

### Steps to reproduce

Run `az containerap create --yaml` using the following YAML file:

```yaml
kind: containerapp
name: myapp
resourceGroup: myresourcegroup
type: Microsoft.App/containerApps
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? /subscriptions/***/resourceGroups/myresourcegroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myidentity
    : {}
properties:
  configuration:
  template:
    containers:
      - image: myacr.azurecr.io/myimage:latest
```

**Expected behavior**
Container app should be created or patched.

**Actual behavior**
I get the following error:
```
ERROR: (InvalidIdentityValues) Invalid value for the identities '/subscriptions/***/resourceGroups/***/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-platform'. The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property.
```

### Additional context

az CLI and extensions versions:

```
 az --version
azure-cli         2.46.0
core                2.46.0
telemetry       1.0.8
Extensions:
front-door      1.0.17
containerapp 0.3.18
account          0.2.5
```
