### ISSUE TITLE
Feature Request: KRM schema

### ISSUE THREAD

**Issue by jsok** [microsoft/azure-container-apps#668]
**Is your feature request related to a problem? Please describe**.  

The container apps schema does not conform to KRM style.
The precludes the use of many popular tools which work generically with KRM resources (e.g. skaffold, crossplane, knative, etc.).

Adopting KRM would enable users to use other tools and possibly allow Microsoft to reduce the effort in maintaining a bespoke schema and all the associated tooling.

**Describe the solution you'd like**.    

Support a KRM schema, rather than having to specify:

```yaml
type: Microsoft.App/containerApps
tags:
  foo: bar
configuration: {}
properties: {}
```

a more familiar and compatible schema would be like:

```
apiVersion: v1
kind: containerApp
metadata:
  labels:
    foo: bar
spec: {}
```

**Describe alternatives you've considered**.   

Not familiar with any other open and widely accepted schemas.

**Additional context**.  

N/A
