### ISSUE TITLE
Github actions not restoring private github packages. 

### ISSUE THREAD

**Issue by msiskasmith** [microsoft/azure-container-apps#706]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
A clear and concise description of the observed issue.
Github build actions for Azure Container App not restoring private nuget packages
### Steps to reproduce
1. .. created github action for building and deploying a container app to Azure Container App and Container Resgistry
2. .. added a nuget.config file in repository
3. .. initially I only added the path to the Private Package repo, but the nuget.org packages stopped restoring, so I added both my github package links and nuget.org links and my packages are not restoring. The following are the github actions

```
steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: rekruteqacr.azurecr.io
          username: ${{ secrets.REKRUTEQSTATISTICSWEBAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.REKRUTEQSTATISTICSWEBAPI_REGISTRY_PASSWORD }}
       
      - name: Restore NuGet packages
        run: dotnet restore --configfile nuget.config

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rekruteqacr.azurecr.io/rekruteqstatisticswebapi:${{ github.sha }}
          file: ${{ github.WORKSPACE }}/Rekruteq.Statistics.WebApi/Dockerfile
          context: ${{ github.WORKSPACE }}/Rekruteq.Statistics.WebApi
```
Expected the project to build a container image and deploy to azure container app

got error message 
```
#13 [build 4/7] RUN dotnet restore "Rekruteq.Statistics.WebApi/Rekruteq.Statistics.WebApi.csproj"
#13 0.863   Determining projects to restore...
#13 2.254 /src/Rekruteq.Statistics.WebApi/Rekruteq.Statistics.WebApi.csproj : error NU1101: Unable to find package Afrojptech.NetCore.Helpers. No packages exist with this id in source(s): nuget.org
#13 2.255 /src/Rekruteq.Statistics.WebApi/Rekruteq.Statistics.WebApi.csproj : error NU1101: Unable to find package Rekruteq.DataModels. No packages exist with this id in source(s): nuget.org
#13 2.365   Failed to restore /src/Rekruteq.Statistics.WebApi/Rekruteq.Statistics.WebApi.csproj (in 1.21 sec).
#13 ERROR: process "/bin/sh -c dotnet restore \"Rekruteq.Statistics.WebApi/Rekruteq.Statistics.WebApi.csproj\"" did not complete successfully: exit code: 1
```
