### ISSUE TITLE
Configure DAPR to send trace to a custom open telemetry collector

### ISSUE THREAD

**Issue by iamdanthedev** [microsoft/azure-container-apps#710]
Is it possible to configure DAPR with the following configuration? I would like it to send traces to my open telemetry collector running as an application inside the environment that would export traces to Elastic APM. 

```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    otel: 
      endpointAddress: "https://..."
```

**Comment by akoufa** [comment]
Yes please enable this feature for Container Apps. We are currently sending traces to New Relic and we are not seeing the connection between the different microservices due to that the http calls are being proxied throug dapr. We would like to be able to configure the following properties:

```
tracing:
  samplingRate: "1"
  otel: 
    endpointAddress: "https://..."
  zipkin:
    endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
```

in the Bicep Dapr Configuration for the Container App
