### ISSUE TITLE
Question: zero-replica App without KEDA rules being started upon Azure Service Bus message. How it happens?

### ISSUE THREAD

**Issue by CezaryKlus** [microsoft/azure-container-apps#78]
Hi,

This is more like a question as things are not clear to me. I have a Container App meant for background processing of some Azure Service Bus messages. There are no scaling rules defined:
```
    "scale": {
      "maxReplicas": 10,
      "minReplicas": 0,
      "rules": null
    }
```

I see in logs that after some short time replica count goes from `1` to `0` as expected - it effectively means the process exited, does it? In the logs I see MassTransit diag messages showing clearly that listening on the queues has stopped.
Once the message arrives to the Azure Service Bus queue which that App was listening on - the App is being started and message processed. All reported in log analytics and in AI additionally.
Interestingly during message processing time replica count is still reported as: `0`.

How this happens? In particular how Azure Container App engine knows when to schedule apps based on messages arrival?
Why the replica count in Azure Portal still reports `0` when clearly App is being started.

Thanks

**Comment by KrzychuR** [comment]
Good question! I'd like to know also, if there is any warm up delay needed to spin up first instance in this case.

**Comment by ahmelsayed** [comment]
@CezaryKlus I can't really explain that. If you can share the environment name or something I can look at the logs for your env.

**Comment by ahmelsayed** [comment]
@KrzychuR for an app that needs to be activated on an azure service bus queue, the application will scale from 0 to 1 when any messages are detected on the queue. The queue polling interval is 30 seconds. Once the pod is assigned to the app, the application containers will take some amount of time to start, depending on the app. 

Does this answer your question?

**Comment by CezaryKlus** [comment]
Hi @ahmelsayed unfortunately I'm now done with Container Apps experiments. Can you make it clear what is the prerequisite for the container app to scale from 0 to 1 assuming it listens on Azure Service Bus queue and message arrives? Is this an autoscaling rule being set up? Or happens (magically) without it as well?

**Comment by KrzychuR** [comment]
@ahmelsayed thanks for reply. Similar to @CezaryKlus I'd like to know more how ACA know it. Base on some logs/history? So for example app has to at least try to listen to BUS to be spine up later?

**Comment by ahmelsayed** [comment]
If you want to deploy a container image, say `myacr.io/processors/queue-processor:v1`, that's processing service bus messages and you want it to only run when there are messages on the queue (scale between `0 <-> 5` instances), you can deploy an app that looks like this in ARM

```json
{
  "properties": {
    "kubeEnvironmentId": "/subscriptions/{id}/resourceGroups/{group}/providers/Microsoft.Web/kubeEnvironments/{name}",
    "configuration": {
      "secrets": [
        {
          "name": "service-bus-connection",
          "value": "Endpoint=sb://sb.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=S08mK3=="
        },
        {
          "name": "docker-password",
          "value": "passwordValue"
        }
      ],
      "registries": [
        {
          "server": "myacr.io",
          "username": "myuser",
          "passwordSecretRef": "docker-password"
        }
      ]
    },
    "template": {
      "containers": [
        {
          "image": "myacr.io/processors/queue-processor:v1",
          "name": "queue-processor",
          "env": [
            {
              "name": "SERVICE_BUS_CONNECTION",
              "secretRef": "service-bus-connection"
            }
          ]
        }
      ],
      "scale": {
        "rules": [
          {
            "name": "serviceBusScalingRule",
            "custom": {
              "type": "azure-servicebus",
              "metadata": {
                "topicName": "mytopic",
                "queueLength": 20
              },
              "auth": [
                {
                  "secretRef": "service-bus-connection",
                  "triggerParameter": "connection"
                }
              ]
            }
          }
        ],
        "minReplicas": 0,
        "maxReplicas": 5
      }
    }
  }
}
```

or in yaml if that's easier to read

```yaml
properties:
  kubeEnvironmentId: /subscriptions/{id}/resourceGroups/{group}/providers/Microsoft.Web/kubeEnvironments/{name}
  configuration:
    secrets:
    - name: service-bus-connection
      value: Endpoint=sb://sb.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=S08mK3==
    - name: docker-password
      value: passwordValue
    registries:
    - server: myacr.io
      username: myuser
      passwordSecretRef: docker-password
  template:
    containers:
    - image: myacr.io/processors/queue-processor:v1
      name: queue-processor
      env:
      - name: SERVICE_BUS_CONNECTION
        secretRef: service-bus-connection
    scale:
      rules:
      - name: serviceBusScalingRule
        custom:
          type: azure-servicebus 
          metadata:
            topicName: mytopic
            queueLength: 20
          auth:
          - secretRef: service-bus-connection
            triggerParameter: connection 
      minReplicas: 0
      maxReplicas: 5
```

what you're defining are:

- **secrets** you will be referring to in your app: here we have the service bus connection and the registry key (if needed)
```yaml
secrets:
- name: service-bus-connection
  value: Endpoint=sb://sb.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=S08mK3==
- name: docker-password
  value: passwordValue
```

- **registries** if they are authenticated

```yaml
registries:
- server: myacr.io
  username: myuser
  passwordSecretRef: docker-password
```

- **images** describing your pod, and their env, etc

```yaml
containers:
- image: myacr.io/processors/queue-processor:v1
  name: queue-processor
  env:
  - name: SERVICE_BUS_CONNECTION
    secretRef: service-bus-connection
```

- **scale** rules

```yaml
rules:
- name: serviceBusScalingRule
  custom:
    type: azure-servicebus 
    metadata:
      topicName: mytopic
      queueLength: 20
    auth:
    - secretRef: service-bus-connection
      triggerParameter: connection 
```

This scale rule is what tells container apps that your application needs:
- run when there is a message on topic `mytopic` on service bus defined in `service-bus-connection`
- the `queueLength` property is your `desiredMetricValue` in [hpa's](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details) equation 

```
desiredReplicas = ceil[currentReplicas * ( currentMetricValue / desiredMetricValue )]
```

with `desiredReplicas` being between the defined:

```yaml
      minReplicas: 0
      maxReplicas: 5
```

The scale rule definition is that of [KEDA](https://keda.sh/docs/2.5/scalers/), where you can also see the supported scalers and their metadata. For example, if you want to scale based on a rabbitmq queue instead of service bus, your scale rule will look like 

https://keda.sh/docs/2.5/scalers/rabbitmq-queue/

```yaml
secrets:
- name: rabbitmq-connection
  value: amqp://guest:password@myredis.server.company.com:5672/vhost
[...]
  rules:
  - name: my-rabbitmq-rule
    custom:
      type: rabbitmq
      metadata:
        protocol: auto
        mode: QueueLength # QueueLength or MessageRate
        value: "100" # message backlog or publish/sec. target per instance
        queueName: myqueue
      auth:
      - secretRef: rabbitmq-connection
        triggerParameter: host
```

or the result of a mssql or postgresql scaler query:

```yaml
secrets:
- name: sql-connection-string
  value: Server=myServerAddress;Database=myDataBase;User Id=myUsername;Password=myPassword;
[...]
  rules:
  - name: my-mssql-rule
    custom:
      type: mssql # or postgresl
      metadata:
        query: "SELECT COUNT(*) FROM backlog WHERE state='running' OR state='queued'"
        targetValue: 1
      auth:
      - secretRef: sql-connection-string
        triggerParameter: connectionString
```
