### ISSUE TITLE
Internal Envoy unable to reach any upstream

### ISSUE THREAD

**Issue by AndrewNikolin** [microsoft/azure-container-apps#809]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [X] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I'm right now working on a project where there is a consideration to use our own Envoy instance to implement routing inside App Container Environment and also to use Envoys external auth with GRPC. Right now the problem I'm noticing is that Envoy docker image running as one of the Container Apps is unable to serve any upstream request directly to any other HTTP container and fails grpc requests to container with envoys external auth implementation. Here is the part of our envoy.yaml configuration for one of the HTTP services
```
- name: api
      connect_timeout: 3s
      type: strict_dns
      lb_policy: round_robin
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: api
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: ${ENVOY_API_ADDRESS}
                      port_value: ${ENVOY_API_PORT}
```
For address configuration sets using `.internal` fqdn with port 433
Any request which is then trying to reach that another container app gets response of 
`upstream connect error or disconnect/reset before headers. reset reason: connection termination`

Is this supposed to be anywhere near possible to set up at all?

### Steps to reproduce
1. ..
2. ..

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         

### Additional context
Ex. Did this issue occur in the CLI or the Portal?
