### ISSUE TITLE
Issue with Azure Container Apps (ACA) Limitation on Opening Multiple Ports

### ISSUE THREAD

**Issue by dummy-andra** [microsoft/azure-container-apps#891]
**Issue Description**

According to the documentation [here](https://learn.microsoft.com/en-us/azure/container-apps/ingress-overview#additional-tcp-ports), it is mentioned that we can open additional TCP ports on Azure Container Apps (ACA), with a maximum of 5 additional ports per app. However, when attempting to open multiple ports per app, I encountered a limitation where only one port per app is allowed.

**Is there any solution to implement a solution in ACA to deploy apps that require multiple ports?**

**Example Scenario:**
Consider the following Docker command as an example:
```shell
docker run -p 90:90 -p 310:310 -p 456:456 <image_name>:<version>

**Comment by ahmelsayed** [comment]
if you're using the cli, you can create such app on ACA using 

```yaml
properties:
  environmentId: '{Your Env Id}'
  configuration:
    ingress:
      # set `external: true` if you want to be able to access these ports from _outside_ the environment.
      # setting it to `external: false` means this is only available to apps running _inside_ the environment. 
      external: false
      targetPort: 90
      exposedPort: 90
      transport: tcp
      allowInsecure: false
      additionalPortMappings:
        # you can have up to 5 additional port mappings in here
        - external: false
          targetPort: 310
          exposedPort: 310
        - external: false
          targetPort: 456
          exposedPort: 456
  template:
    containers:
      - name: my-app
        image: <image_name>:<version>
    scale:
      minReplicas: 1
      maxReplicas: 1
```

Then create your app using 

```bash
az containerapp create \
    --name <app-name>
    --resource-group <resource-group> \
    --yaml /path/to/app.yaml # file with above content.
```
