### ISSUE TITLE
Support for custom sidecar/init containers

### ISSUE THREAD

**Issue by SatyKrish** [microsoft/azure-container-apps#9]
We retrieve secrets from hashicorp vault using `vault-agent` that runs as init/sidecar container. Does Azure Container Apps support running custom sidecar container? Please provide documentation for reference.

**Comment by vturecek** [comment]
Yup, you can run multiple containers in a pod, see here for an overview and limitations: https://docs.microsoft.com/azure/container-apps/containers

**Comment by SatyKrish** [comment]
Thanks for the documentation, will try this out. Can we reuse existing yaml manifests for deployment, services and config maps, or they must be template json?

**Comment by vturecek** [comment]
if you mean Kubernetes manifests (e.g., deployment, service) , then no, we don't support deploying a Kubernetes manifest directly to Container Apps. Container Apps uses a simplified deployment manifest that combines some of the functionality of various Kubernetes manifests into a single application object (e.g., ingress, pods, replica count, etc.). You can see the full spec here: https://docs.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec

Also note that JSON isn't necessarily your only option. You can use [Azure Bicep](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview) instead of JSON if you're deploying a template, or you can use the same schema in a YAML file when using the Container Apps CLI: 

```
az containerapp create --yaml myapp.yaml
```

**Comment by SatyKrish** [comment]
Do you support configMaps? How can we provide custom configurations to Container App?

**Comment by SatyKrish** [comment]
> you can use the same schema in a YAML file when using the Container Apps CLI:
> 
> ```
> az containerapp create --yaml myapp.yaml
> ```

Thanks. Tried the following manifest for multi-container app and it worked. There is lack of documentation about using TCP port in container template. Also couldn't find documentation for `yaml` spec. Will raise a different issue for that,

```yaml
type: Microsoft.Web/containerApps
template:
  containers:
  - name: redis
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    env:
    - name: TCP_PORT
      value: 6379
    - name: ALLOW_EMPTY_PASSWORD
      value: 'yes'
  - name: vote
    image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
    env:
    - name: HTTP_PORT
      value: 80
    - name: REDIS
      value: localhost
  scale:
    maxReplicas: 1
    minReplicas: 1
kubeEnvironmentId: /subscriptions/5c8f3e12-757e-4183-a8d0-80effb7bf97f/resourceGroups/saty-containerapps/providers/Microsoft.Web/kubeEnvironments/saty-containerapps-env 
configuration:
  activeRevisionsMode: Multiple
  ingress:
    external: true
    targetPort: 80
```
