### ISSUE TITLE
Feature Request: Run multiple containers inside one container app job

### ISSUE THREAD

**Issue by ahmedkhan50** [microsoft/azure-container-apps#915]
Hi, 

I am using container app job to run a headless selenium script, I wanted to know how we can run multiple such containers with different images in same container job ? Is this a good idea to have multiple containers inside a single job ? Please let me know ?

**Comment by vturecek** [comment]
Yes, you can run multiple containers in a single job. Just like with apps, a job runs a "pod" of containers, which all share a network namespace (they can communicate over localhost).

If you look at the example ARM template here, you'll see that `properties.template.containers` is an array where you can add multiple container specs: https://learn.microsoft.com/azure/container-apps/jobs?tabs=azure-resource-manager#event-driven-jobs

**Comment by ahmedkhan50** [comment]
Ok, we use az cli to create resources, so using cli how do we create
multiple containers inside a job ?

**Comment by p-bouchon** [comment]
You can use the `--yaml` option on the cli with either `az containerapp job create` or `az containerapp job start` to specify multiple containers in the same job as seen here https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-cli#start-a-job-execution-on-demand

I've just tested creating a job with multiple containers with the yaml option and confirmed it is behaving as expected


```
location: your region
properties:
  environmentId: /your/env/id
  configuration:
     triggerType: Manual
     replicaRetryLimit: 1
     replicaTimeout: 100
     manualTriggerConfig:
       repllicaCompletionCount: 1
       parallelism: 1
  workloadProfileName: Consumption
  template:
    containers:
      - image: nginx
        name: nginx1
        resources:
          cpu: 0.5
          memory: 1Gi
      - image: nginx
        name: nginx2
        resources:
          cpu: 0.5
          memory: 1Gi
    scale:
      minReplicas: 1
      maxReplicas: 2
```
